### ISSUE TITLE
Weird booster + projection bug.

### ISSUE THREAD

**Issue by lord-carlos** [DarkFenX/Pyfa#116]
0.) Open a ship with damps on it.
0.1) Give that ship boost from *booster A*
1.) Open ship B and project the first ship onto it.
2.) Give it also boost from *booster A*

**Result:**
Nothing happens.

**Expected Result:**
Lock range should increse.

~~If the booster skill is set to *All 0* the Bonus from *All V* gets applied.~~
![image](https://cloud.githubusercontent.com/assets/155855/3166316/773a9e48-eb5f-11e3-94fa-90f15ff84c73.png)

~~Should be the other way around.~~
If they have different boosters everything is fine.
**DL;DR** If two ships project something to each other and have the same booster, one of them does not get any boost.

**Comment by blitzmann** [comment]
I'm going to close this as I cannot really reproduce, and I've don'e a lot of work on projections and calculations which I have a feeling may have solved this regardless. Please reopen if it's still an issue. e74e2615ad45f00a200477e880e61b67e6f153eb
