### ISSUE TITLE
Quickly fitting modules using shortcuts

### ISSUE THREAD

**Issue by lunedis** [DarkFenX/Pyfa#183]
Example procedure:
1) Type "10mn micro" into the market search
2) See list of possible MWDs with 1) or 2) in front of them
3) Fit the experimenttal mwd (2nd in list) using for example "alt+2". It gets fitted to the first free medslot
4) ctrl+a and erase search, search new item, repeat.

This allows you to fit a lot of modules really quickly, without having to use the mouse.
EFT has that feature (using CTRL+number), it's called "enable fitting shortcuts" there.

**Comment by blitzmann** [comment]
I noticed that you started work on this on your own branch. I have not tried it yet, but it looks like it could be promising. If you are still interested in developing it, let me know and shoot over a pull request when ready. If you have abandoned it, I can evaluate your current progress and see if we can incorporate your changes into master.

**Comment by lunedis** [comment]
I implemented it two times: first very rough to test the functionality, second time better with nicer code (with lists and stuff, whee).

The idea was basically to import the ItemSelected event from the market browser and then just copy the code from the existing shortcuts in order to connect ALT+number to the selecting the specific item in the list.

I have not done any UI changes.
Works fine though, I use it everyday.

**Comment by blitzmann** [comment]
I've tried your code, works fine. Feel free to submit a pull request, and maybe I can clean it up in the gui

**Comment by blitzmann** [comment]
You might need to apply the patches to a branch that is off the vanilla pyfa master, and use that as your pull request. Since there have been many merges since your changes, not sure if the pull request would work. Worth a shot tho =)

**Comment by blitzmann** [comment]
Merged, thanks! Hopefully this will be useful to others as well.

I developed a simple way to convey the shortcut in the module list. There will be a toggle to turn it on if the user finds it helpful (but default will be off):

![capture](https://cloud.githubusercontent.com/assets/3904767/8506490/c562d56a-21e4-11e5-921d-285e0976a142.PNG)
