### ISSUE TITLE
Damage application graphs not working on OSX 10.8.5

### ISSUE THREAD

**Issue by Insurgencygame** [DarkFenX/Pyfa#234]
This has been an ongoing issue for the last several releases. 

It did work in v 120 

I when you click on graphs from the menu there is no response

**Comment by blitzmann** [comment]
Are you running pyfa from source or from the release package?

From my testing on my OS X VM, I can open graphs when running from release (which includes python interpreter and all modules needed). If you are running from source, you should make sure you have proper modules installed. Take a look here and see if this helps at all: #40

**Comment by Insurgencygame** [comment]
Hi I am running it from the release package.

I have not tried v1.9 yet

**Comment by glguy** [comment]
I had a problem like this on OS X after I moved the application bundle. Running pyfa with stderr visible showed that some font (iirc) paths had absolute paths registered for the original location where I'd executed pyfa.app and they were no longer working once I'd moved it into /Applications. In my case I fixed it by deleting the cache files associated with whatever library it was related to at the time.

(Just throwing this out there as a possibility)

**Comment by blitzmann** [comment]
Finally got a hackintosh going. @glguy seems to be right, although I have not been able to get it to print out an error yet. It seems to be somewhat difficult to reproduce - running it from Downloads and graphs open fine. Then if I move the app to the Applications folder, graphs don't work. If I move it to the desktop, again graphs don't work. Move it back to the Downloads and it works.

And then I tried the desktop again and it worked. Very odd. @glguy, you probably know more about osx than me. how did you get it to print stderr/out from inside the package? I try to run it from source and even through my interpreter through the .app itself, and it always works.

**Comment by blitzmann** [comment]
Well, I got something: http://pastebin.com/fUECwM6A

Seems to suggest something about the fonts like @glguy reported. This leads to interesting questions such as why the hell does this only affect the graphing. Where are the cache files that need to be downloaded? And what exactly can be done to prevent this. Looking into it =)
