### ISSUE TITLE
Item prices are empty

### ISSUE THREAD

**Issue by infoman** [DarkFenX/Pyfa#238]
Price update seems to be broken for me in 1.7.1 release. It just shows 0.0 as total price and empty price column in fitting window.

Some issues with pricing existed even before this release, but after module removing and re-adding the prices were usually updated, now they are not.

Nothing is printed in console when I launch pyfa from command line.

**Comment by blitzmann** [comment]
@infoman just pushed a fix -- essentially just using `https://eve-central.com/api/` without the `api` subdomain. If this doesn't work, please let me know. =)
