### ISSUE TITLE
Capchain support, e.g. for logistics

### ISSUE THREAD

**Issue by Nothing4You** [DarkFenX/Pyfa#244]
Hey there,
I noticed that I couldn't find where I could set up a partner for a capchain to see cap status e.g. for capchaining logistics.

**Comment by Iiridayn** [comment]
You can right click on a module and choose "Project Module onto Fit". It will then show up under the "Projected" tab under "Additions" at the bottom of the fit.

**Comment by blitzmann** [comment]
You can also project a fit onto another fit, which will take into consideration hull bonuses and character skills. Simply drag a fit from the ship browser to the projection list (I should probably make a context menu similar to aforementioned module projection)

The only caveat is that you cannot have a projection loop, such as `A -> B -> A`, or even `A -> B -> C -> A` (see #72). You can accomplish this by copying A as A' and doing `A -> B -> A'`

**Comment by Nothing4You** [comment]
Thank you very much for this info.
Somehow missed it on the FAQ.
And thanks for the headsup with #72.
