### ISSUE TITLE
Tooltips for fitting window columns?

### ISSUE THREAD

**Issue by BartMassey** [DarkFenX/Pyfa#245]
Some of the columns on the fitting window are pretty mysterious, and I haven't found any documentation that explains them. A tooltip on each column icon could go a long way toward helping out here. (Also making sure each column has an icon.)  Pyfa 1.6 on Linux.

**Comment by blitzmann** [comment]
Well, I would think that PG, CPU, and Cap usage is pretty self explanatory (however, I've never noticed that the cap icon is the same as powergrid - I can probably fix this easily). The next column is the "misc" column, displaying information depending on the module (missiles show sig radius and velocity, webs show % slowdown, etc). Those have tooltips. And then price is, again self explanatory.

If it's easy to add tooltips to the ones that don't I don't see why not. Will take a look at it.

**Comment by BartMassey** [comment]
Cool. Thanks! I couldn't figure out the "misc" column: makes sense now. I figured out the Cap one, but yes, the choice of icon made it take me longer than it probably should have. Adding units to the stuff in the misc column would be a nice followup: would also help figure out what's going on.

**Comment by blitzmann** [comment]
Some of the stuff doesn't really need units. I welcome any recommendations on what should change to make it easier (within the space constraints)

**Comment by BartMassey** [comment]
I'm guessing the misc for turrets is effective tracking in rad/s ? That is a little unwieldy, although θ/s might be doable. What is the misc number for a Core Probe Launcher? Mine says 7.1 of something...

Don't worry about it; I'll look at the source and propose a patch if I get motivated. EvE is hard. Thanks much for your hard work on making it easier. Greatly appreciated.

**Comment by blitzmann** [comment]
Misc column info can be found here: `gui/builtinViewColumns/misc.py`. It's actually pretty straigtforward to change things, feel free to recommend improvements.

Also, for probe launcher, I believe the number shown is probe strength. I have no idea how to unit that, but it should show as the tooltip. =)

**Comment by blitzmann** [comment]
Also added info for state. Hover over the module checkmark and it should say "Active". Ctrl click and it will change to "Overheated". Simple.

**Comment by BartMassey** [comment]
Thanks!
