### ISSUE TITLE
Showing "average resistance multiplier"

### ISSUE THREAD

**Issue by lunedis** [DarkFenX/Pyfa#248]
The "average resistance multiplier" is calculated either by dividing EHP by HP or using the average reciprocal of every resistance.
Example:
A ship with average resists of 85% has a multiplier of 1 / (1 - 0.85) = 6.66.

Together with #235 you can even calculate tanked DPS yourself quickly (tank = hp/s * resist multiplier) or compare it between different fits / ships.

EFT shows the value in a tooltip while hovering over the respective tank icon ([picture](http://i.imgur.com/bIgmddr.png)).

**Comment by BlckKnght** [comment]
The tank amounts for the current ship shown in the "Recharge Rates" panel are, by default, in EHP/s, not raw HP/s (though you can click the "EHP" button to switch to raw HP if you want). If you want to know about how your ship will respond to remote reps, drag a logi ship into the "Projected" tab and the displayed rates will include the remote reps from that ship.

I'm not saying there's no use to the multiplier, but I'm not sure it's urgently needed, since there are other (better!) means of getting the information you want in the end.

**Comment by lunedis** [comment]
I did a very crude implementation of this, I'm not sure how to integrate it into the UI nicely though or of that way is a good way to calculate it.

see https://github.com/lunedis/Pyfa/commit/41edc821b1d88dced81d207c16cb04350091e17b

http://i.imgur.com/v6vT0oF.png

**Comment by blitzmann** [comment]
Walk me through the usefulness of knowing an "average resist multiplier". From what I understand, it's useful for knowing about remote reps, but as previously stated this information is already available (it much more detail) with fit/module projection.

I'll take a look at your commit - it's pretty simple and harmless to implement, especially if folks get use out of it, but I'm curious what I'm missing about it. =)

As for GUI, tooltip is indeed the best way as there is nowhere else. I would recommend creating a newline and putting `Avg. Resist: x#.##` to describe what it is (kind of like eft does)

**Comment by lunedis** [comment]
Knowing the multiplier (or "rr factor" as Kadesh calls it) is helpful for comparing fittings and manually calculating repped DPS.

Comparing fittings using the multiplier is much easier than using the resists manually or projecting a fit onto it every time. You can easily tell a Sacrilege with rr factor of 6.00 tanks 50% more than a vexor with a multiplier of 4.00 without needing to find a logi fit and project it.

As you can't project one fitting multiple times and the UI for projecting is a bit slow (find logi ship, drag into projection, find next logi ship, drag into projection, ...) the rr factor would be useful there.

Before I built a tool for that myself I actually had spreadsheets for calulating the DPS tanked for every ship in a RR gang / gang with logi.
Calculating that requires no complex library as eos, as rr factor * hp/s immediately gives the DPS tanked. In EFT I could just read the rr factor from the tooltip, in Pyfa I had to manually divive EHP by HP.

**Comment by blitzmann** [comment]
Thanks for the write up, it did help to clarify things. Go ahead and create a pull request. As for the format, here's what it might look like with a new line
![untitled](https://cloud.githubusercontent.com/assets/3904767/8553750/9019e8f4-24b3-11e5-970d-0704e5191000.png)

I'll leave it to you to decide which you think is best, as I can't decide lol. ;)

**Comment by blitzmann** [comment]
Also, my next focus actually revolves around projected fits to make them easier to work with. keep up with #83
