### ISSUE TITLE
DPS Graph window does not load (FreeBSD)

### ISSUE THREAD

**Issue by f-andrey** [DarkFenX/Pyfa#250]
Hello, I'm test porting Pyfa for FreeBSD
base functional work fine,  DPS Graph window does not load similar #40 
```shell
# python -c "import matplotlib as m; print(m.__version__); print(m.__path__[0]);"             
1.4.0
/usr/local/lib/python2.7/site-packages/matplotlib
# python -c "import numpy as m; print(m.__version__); print(m.__path__[0]);"                  
1.9.1
/usr/local/lib/python2.7/site-packages/numpy
# python -c "import wx as m; print(m.__version__); print(m.__path__[0]);"
2.8.12.1
/usr/local/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx
```
If change gui/graphFrame.py https://github.com/DarkFenX/Pyfa/issues/40#issuecomment-35224589 when you attempt to open Graphs.
```shell
Import can't find module, or can't find name in module.
/lib/libgcc_s.so.1: version GCC_4.6.0 required by /usr/local/lib/gcc48/libgfortran.so.3 not found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pyfa/gui/mainFrame.py", line 689, in openGraphFrame
    self.graphFrame.Show()
  File "/usr/local/lib/python2.7/site-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 9143, in Show
    return _core_.Window_Show(*args, **kwargs)
TypeError: in method 'Window_Show', expected argument 1 of type 'wxWindow *'
```
whether it is possible to get something more diagnostic information?

**Comment by reactormonk** [comment]
Tried installing gcc-fortran?

**Comment by f-andrey** [comment]
Yes
```shell
# pkg which /usr/local/lib/gcc48/libgfortran.so.3
/usr/local/lib/gcc48/libgfortran.so.3 was installed by package gcc-4.8.4
```
previously had a problem with a similar diagnosis https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=188114  but now it seems to be fixed because the package "numpy" is loaded correctly

**Comment by f-andrey** [comment]
It looks like the cause of the error found, tests examples/py-matplotlibuser_interfaces/embedding_in_wx2-4.py are passed correctly, but examples/py-matplotlibuser_interfaces/embedding_in_wx5.py gives a similar error, I will open the query to correct

**Comment by blitzmann** [comment]
I'm closing this as it seems to me not to be a pyfa issue (tho it may have gone over my head). Feel free to reopen if you need to =)
