### ISSUE TITLE
Wrong Nomad implant set value

### ISSUE THREAD

**Issue by Wowl** [DarkFenX/Pyfa#253]
The Mid-grade Nomad implant set appears to have an incorrect value associated with it. The full set should give an agility bonus of ~26,931% but is currently giving less. My calculations are according to http://oldforums.eveonline.com/?a=topic&threadID=203472 - if you have any other (better) base on which those calculations are done it'd be great if you shared!

**Comment by blitzmann** [comment]
Can you provide a bit more detail? You expect 26.9% modification, what is the actual modification that you get? Can you provide a fit?

**Comment by blitzmann** [comment]
On pyfa currently: confessor in defense mode and all 0 skills has an agility multiplier of 2.15x. If we apply all mid-grade Nomad implants, this drops down to 1.571x, which is ~-26.9%, which is what it should give. So this is working as intended. Please reopen if you believe this is not that case
