### ISSUE TITLE
As of 1.8.1 on OSX, pyfa still lists 'Inertial Stabilizers II' instead of 'Inertia Stabilizers II'

### ISSUE THREAD

**Issue by fucema** [DarkFenX/Pyfa#254]
I can see there is a DB migration to sync module names updated in the Proteus tiercide effort (located at eos/db/migrations/upgrade4.py), but in my OSX pyfa version 1.8.1, the modules are still using the older name.

Is it possible that 1.8.1 was released before the db migration script was applied or available? 

I am still looking into fixing this for my local copy, but would like to know if I am off-target or incorrect about these module names and 1.8.1 Thanks!

**Comment by blitzmann** [comment]
I just tested on my OS X VM, and I have the proper renames. Make sure you are running v1.8.1. Provide screenshots if you can. =)

There is one module that they seemed to have missed: "Synthetic Hull Conversion Inertia Stabilizers", but that would be on CCPs end

Also, the database migration simply converts modules that have been removed / unpublished from EVE to their new modules. The actual renames are automatically included when the data is extracted from the client -- we don't touch the names. We also have a conversion mappings in `service/conversions` for when you are importing old module names that will (hopefully) convert them to the needed module.

**Comment by fucema** [comment]
I will update with an OSX screenshot and confirm it is 1.8.1 tomorrow (laptop is unavailable at the moment).

Here is a screenshot from WINDOWS however, that shows the same issue. Version 1.8.1 and Inertial. ![Image of Windows 1.8.1](http://i.imgur.com/DDpk7Kl.png)

My windows installation and osx installation is using a shared .pyfa data folder (sync'd via DropBox).

**Comment by fucema** [comment]
Here is a screenshot from pyfa running on my osx. 

![Image of Osx 1.8.1](http://i.imgur.com/h1UYNmy.png)

**Comment by blitzmann** [comment]
i think you misunderstood the rename of these modules. They were all renamed from inertia to inertial, except one module. So inertial is actually the proper name. From the devblog:

> Inertial Stabilizers are now consistently named Inertial Stabilizers instead of some being Inertia Stabilizers and some Inertial Stabilizers.

Hope this helps. Closing issue. =)

**Comment by fucema** [comment]
Thanks for the clarification. I had the renaming swapped obviously!

Cheers
