### ISSUE TITLE
Crashes on startup

### ISSUE THREAD

**Issue by Lukas45** [DarkFenX/Pyfa#257]
Recently Pyfa is starting to crash whenever I open the app. Nothing really happens, no window or anything. I double click the icon, and it instantly crashes. I think it started happening after my laptop ran completely out of power (shut completely down, not just partly) while Pyfa was open with a fit.
Windows crash error
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	pyfa.exe
  Application Version:	0.0.0.0
  Application Timestamp:	49180193
  Fault Module Name:	sqlalchemy.cresultproxy.pyd
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	4e9b307d
  Exception Code:	c0000005
  Exception Offset:	000012aa
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1030
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by blitzmann** [comment]
Delete sqlalchemy.cresultproxy.pyd. this is a known issue and happens a lot: https://github.com/DarkFenX/Pyfa/wiki/APPCRASH-sqlalchemy-.pyd-files

We've been meening to rebuild Windows skeleton files for some time, which should fix issue.
