### ISSUE TITLE
Activating/deactivating missile launcher modules affects capacitor stability when displaying a percentage

### ISSUE THREAD

**Issue by OISumeko** [DarkFenX/Pyfa#261]
When fiddling with a fit, I noticed that when I toggled the fitted 'Rocket Launcher II' module between active and inactive, the capacitor stability reading changed. This struck me as odd, as (to the extent of my knowledge) these modules shouldn't affect capacitor. The fit I was using when I first noticed this is as follows:

    [Jaguar, SampleFit]
    
    Gyrostabilizer II
    Internal Force Field Array I
    Micro Auxiliary Power Core I
    Overdrive Injector System II
    
    J5b Phased Prototype Warp Scrambler I
    Limited 1MN Microwarpdrive I
    Medium Ancillary Shield Booster, Navy Cap Booster 50
    Medium F-S9 Regolith Shield Induction
    
    150mm Light AutoCannon II, Republic Fleet Phased Plasma S
    150mm Light AutoCannon II, Republic Fleet Phased Plasma S
    150mm Light AutoCannon II, Republic Fleet Phased Plasma S
    Rocket Launcher II, Caldari Navy Nova Rocket
    
    Small Anti-Kinetic Screen Reinforcer I
    Small Projectile Burst Aerator II

With all modules enabled, and the 'All 5' character selected, the capacitor reads as Stable at 32.5%. When the Rocket Launcher is toggled off, the capacitor reads as Stable at 36.7%. The Capacitor total, as well as recharge/discharge rates do not change.

I tried multiple characters with the same fit, and found the same effect occurred when the stability was displayed as a percentage. However, if the stability was displayed as MM:SS (eg. 4m0s), then no change was seen when toggling the module. 

I tried fitting up a crow in a similar fashion, and encountered the same issue. In addition I fit up a caracal, and tried all available MIssile Launcher varieties (LML, RLML, TP, etc) as well as a number of named varieties of launchers -- all of these exhibit the same issue.

I also checked with a number of fits to see if this behaviour was present with projectile turrets, and did not note any issues, so this issue does seem to be limited to launchers.

**Comment by blitzmann** [comment]
You seem to be describing #126, however that should have been fixed a while ago. I have not yet tested your fit or reproduction steps yet (thank you for being so detailed). In the meantime, can you confirm that you are using the latest pyfa version (v.1.8.1).

**Comment by OISumeko** [comment]
I am using the latest release (v. 1.8.1) on Windows 7, 64 bit. Sorry for missing that on the original report!
