### ISSUE TITLE
Suggestion: Create a "Groups" Tab

### ISSUE THREAD

**Issue by BeAuMaN** [DarkFenX/Pyfa#265]
Hello.

I love this tool, and I tend to recommend it to newbies who are starting out over in Nullsec (I help a number of them over in our coalition). I find that the User Interface is better designed than EFT, not to mention more pleasing to the eye. Then there's that spiffy IGB feature that I have them use to import fits easily.

Anyhow, I had a suggestion: I'd like you to add a "Groups" tab to the program, to the right of the Ships Tab.
![This Picture](http://puu.sh/gGkHQ/f09cef3360.png)

Effectively this would let the user create custom named folders to put a variety of ship fits in. Fits could be part of multiple groups. Ideally this would also include a "Note" section somewhere in that Group for general notes about that group of ships. Where this would be useful is for a great number of pilots who use this program and fly Doctrines. I can create a group for a specific doctrine, organize those ships into that doctrine group, and write down some additional notes for that group in the note section (Perhaps about SRP, ideal use, etc).

This would be a great help, especially to newbies who I recommend this program to. Perhaps there might be a "Group Export/Import" feature as well, but that's really more pie-in-the-sky stuff as import/export features tend to be a pain in the ass I imagine.

Thanks!

**Comment by DarkFenX** [comment]
This sounds like fit tag functionality, it's planned for next-gen pyfa which is currently is in development

**Comment by BeAuMaN** [comment]
Oh, cool! I look forward to it.

**Comment by blitzmann** [comment]
I had the backend of this "tag" feature functional on a local branch, which I have now unfortunately lost from about a year ago. I got stuck with how exactly to convey tagging information to the user graphically - there wasn't a good place to put it that didn't require a fair amount of work. It's something that will have to wait until the next pyfa version is out.
