### ISSUE TITLE
Incorrect Database Entry for 100mn Afterburner II

### ISSUE THREAD

**Issue by tkuhlengel** [DarkFenX/Pyfa#272]
PYFA shows that the 100mn Afterburner II Has the following fields __inconsistent__ with the In-Game info:

* activation cost (in-game 352, pyfa 127)
* Heat Damage (IG 4.10, pyfa 3.28)
* Activation time / duration (IG 10 s, pyfa 8 s)
* Maximum Velocity Bonus (IG 135%, pyfa 162%)

**Screen Shots**

![image](https://cloud.githubusercontent.com/assets/897141/7108615/ff070938-e159-11e4-8309-31be4b592942.png)

![image](https://cloud.githubusercontent.com/assets/897141/7108618/177889a6-e15a-11e4-9aea-403005a72793.png)

**Comment by DarkFenX** [comment]
Seems like you're looking at base attribs ingame and on attribs modified by your skills in pyfa. I'm almost sure that it is an issue (base AB cycle is 10, but you can't really use t2 AB and have cycle of more than 8 seconds - because it needs AB skill at level 4 and AB skill reduces cycle time by 5% each level).

If i'm wrong, reopen the issue.

**Comment by tkuhlengel** [comment]
It appears you are correct.  When I view it today without putting it on a ship, it does match the second image above.  However, since the window was not "clearly" labeled as being skill/ship bonused, and caused a bit of confusion for some of my comrades and I.


It may be useful to have a column in the attributes table of Module Stats window, one column that shows the base value and a second that shows the skill-bonused value on a given ship when showing info on a fitted module.

Either or a button that switches between them would be nice.  Maybe add to the "dream" pile of things to add.

**Comment by JoshuaNotowitz** [comment]
>It may be useful to have a column in the attributes table of Module Stats window, one column that shows the base value and a second that shows the skill-bonused value on a given ship when showing info on a fitted module. 

The "Affected by" tab in your first pictures might be what you are looking for.

**Comment by blitzmann** [comment]
Yeah, the affected by tab is what you're looking for, however I really like the idea of having another column, toggle, or other mechanism to show the effective values. Something to think about for later. =)
