### ISSUE TITLE
Ship mass incorrect

### ISSUE THREAD

**Issue by quasarj** [DarkFenX/Pyfa#275]
I have to imagine I'm just missing something, but why are ship masses incorrect in Pyfa? For example, the Omen shows a mass of 63Gg, however its actual mass as reported in-game is 13Gg.

**Comment by blitzmann** [comment]
You are probably not considering the modules that are currently affecting the ship. In pyfa the Omen is listed as 13,000,000 kg, as it should be, without any modules. However, consider that you add a 1600mm plate onto it - the mass will increase to 15,812,500 kg (with all 5 skill).

Remember that when you show info on something in game, it will most likely show you it's base stats (unmodified my modules or skills). To see the actual attributes, (I believe) you must first undock and then show info on your modules / ship.

Please double check your modules and what you are showing info on. make sure the fit your comparing in pyfa is the exact fir in game. If you are still concerned something is wrong, post EFT fitting and some screenshots of ingame vs pyfa.

Closing this for now, reopen if still unsure. =)

**Comment by quasarj** [comment]
I was pretty sure you were wrong about this.. but you were right! Thank you closing this issue before anyone saw it and furthered my embarrassment! :)
