### ISSUE TITLE
Unable to overheat modules

### ISSUE THREAD

**Issue by nCrazed** [DarkFenX/Pyfa#278]
After installing the latest version from git I am no longer able to overheat modules by right clicking, it appears that right click now behaves exactly the same as left click (activate/deactivate).

**Comment by DarkFenX** [comment]
I just merged wx3 branch, it might contain massive changes to how various events are handled.

Please provide following data:
- Which OS are you using
- Which wxpython versions do you have (list all installed & default)

**Comment by DarkFenX** [comment]
Uhh nevermind. Turns out i have the same issue as well.

- Debian GNU/Linux (gnome 3.14)
- wxpython 2.8.12.1 and 3.0.1.1 (3 being default)

**Comment by DarkFenX** [comment]
I will revert all the commits to master until issues like this are resolved. Going to merge only after wx3 branch is stabilized & 'beta-tested' (i plan to make wx3 preview release sooner or later)

**Comment by DarkFenX** [comment]
Fixed it in wx3 branch. Probably going to merge everything back to master after i fine-tune some details related to binary distributions,
