### ISSUE TITLE
On windows, cursor is not shown in market browser search

### ISSUE THREAD

**Issue by DarkFenX** [DarkFenX/Pyfa#280]
Windows 8.1 x64
wxPython 3.0.2.0

On linux it's shown correctly

**Comment by narthollis** [comment]
Additionally I can not select the contents of the search field.

**Comment by blitzmann** [comment]
Mostly some missing `event.Skip()`s. Please test out the latest wx3 branch on both Windows and Linux with both 2.8 and 3.0 and see if it seems right. I also removed a good chunk of useless Mouse Move code, the original purpose of which I'm not entirely sure, so it would be nice to know if this caused any issues either. Quick test on Win7 shows it's back to it's normal self on both 3.0 and 2.8

**Comment by blitzmann** [comment]
Tested as best I could on all three systems. Works fine. Closing
