### ISSUE TITLE
Installer is not removing old pyfa version before installing new one

### ISSUE THREAD

**Issue by DarkFenX** [DarkFenX/Pyfa#283]
This leaves massive amount of old .py and .pyc files, thus potentially can cause issues like #279.

Implementing proper uninstalling in Inno script is a prerequisite for making distributions with new skeletons (where i'd prefer python files compressed in library.zip, than having multiple thousands of files lying around).

**Comment by DarkFenX** [comment]
As an alternative there's MSI installer generation in cx_Freeze (i checked and it works), afaik it handles it by default. Might use it instead of Inno Setup, if it's hard to implement in Inno.

**Comment by narthollis** [comment]
I can confirm also that clearing my pyfa install folder and reinstalling fixes the issue.

I would think that moving to cx_Freeze MSI would be a better idea in the long run as it means less tools that need to installed/run to have a complete build out the door. I originally suggested Inno Setup as it's what I have some experience with.

**Comment by DarkFenX** [comment]
I am thinking about continuing to use skeleton concept (handy for various preview builds), thus there're good chances we won't be hardwired to cx_Freeze for each release. It opens space for any tool which is able to make installers. We'll see.

**Comment by DarkFenX** [comment]
Ok, so, compiled list of things we have to do regarding packaging:
1) Windows installer should remove files of old pyfa version prior to installing new one
2) It might be possible that now pyfa folder contains alot of files which are not tracked by installer (and to be fair i have no idea if it tracks them at all), thus we should do one-time cleanup of pyfa folder, which should remove all exiting _pyfa_ files (it's super important to remember that there's option --root which makes pyfa to store saveddata in user folder, and we should never touch it).
3) New packaging should use compressed .zip library for python files (to avoid clutter with all these effect files)
4) New skeletons can be built using said .zip library file - we should just get rid of pyfa-specific files from there and add them in the form of .pycs each time we merge pyfa and skeleton into distribution

**Comment by blitzmann** [comment]
The pyfa uninstaller removes everything except the eos, gui, and service directories (but the only remaining files are `.pyo`). It also does not seem to touch the `saveddata` directory.

If we are thinking about using the MSI installer, we would need to make sure that it runs the uninstall first, and then somehow clean up the `.pyo` files. With Inno, there may be a way to remove the pyo files automatically.

It may just be easier to tell the user to delete their own stuff and start over, and remind them to preserve their saveddata if needed

Also, I agree that we should continue the concept of skeletons so that we don't hvae to run cx_freeze every time. That and the fact that cx_freeze needs to be run on the target platform to create the executable...

**Comment by blitzmann** [comment]
For InnoScript, adding this to `[Tasks]`

    Name: extensions; Description: "Register file extensions (.pyo)";

 And then this bit



    [Registry]

    ; Register .pyo
    Tasks: extensions; Root: HKCR; Subkey: ".pyo"; ValueType: string; ValueName: ""; ValueData: "Python CompiledFile"; Flags: uninsdeletevalue
 
Removes `.pyo` files. This was shamelessly stolen from http:t//www.opensource.apple.com/source/python/python-3/python/PCbuild/python.iss and I have no idea what it actually does

This also gives the user an option to register the extension, which we don't want. I'll continue fiddling with it

**Comment by blitzmann** [comment]
This should be fixed as of b454ac003b867497168980874dc80499bf26c3f5
