### ISSUE TITLE
Copying Fit Doesn't Work / Breaks Loading Loadouts

### ISSUE THREAD

**Issue by droppedoncaprica** [DarkFenX/Pyfa#285]
Search for a ship with a fit already saved.  On the fit, click the green `+` icon.  The fit won't duplicate.  After it is clicked, you can no longer load fits that have been saved.

I'm on Windows 10 on the `wx3` release.

**Comment by blitzmann** [comment]
I cannot reproduce with the current wx3 branch on interpreter, however this does happen with the pre-release binary.

**Comment by droppedoncaprica** [comment]
I'll double-check what version of Pyfa I have installed tonight and see if there is a newer build.

**Comment by blitzmann** [comment]
Closing issue - still cannot reproduce. reopen if you experience the issue again
