### ISSUE TITLE
Broken Triage Projection

### ISSUE THREAD

**Issue by Moatman** [DarkFenX/Pyfa#291]
Projecting triage onto a fit seems to be broken as of v1.11.0. I'm not sure how the numbers are being grabbed, but it seems to be using the cap of the ship being repped for sustained rates, which leads to pyfa displaying negative rep amounts on unstable or neuted ships.  
Additionally, projecting a carrier with triage cycling just plain doesn't work. It shows as repairing 300 raw hp per second per rep whether triage is on or off.

**Comment by DarkFenX** [comment]
What do you mean by 'projecting triage onto fit'? Projecting triage-fitted carrier onto fit?

Regarding 2nd point - works for me (thanatos with t2 triage, 2 capital RRs projected onto retribution). Although whole projection/fleet thing is implemented in pyfa as a huge hack, thus providing unreliable results.

Provide full fits for both projector and projectee, any module on fit might affect final RR values.

**Comment by Moatman** [comment]
Yeah, I mean that projecting a triage fitted carrier (with a triage module active) onto a ship fit that isn't cap stable past a certain amount will cause the sustained shield repair value to go negative.
[Triage Chimera](http://imgur.com/Z0sPwz0), [Combat Chimera](http://imgur.com/ylvkbHB), [Combat Chim with hardeners overheated](http://i.imgur.com/WVqiidg.png), [Neuted Ishtar](http://imgur.com/06bxpQi), and [Combat Chimera raw values](http://imgur.com/RxM2WWU). 
That last one should be a bit less than 5000 while in triage instead of 1200.

**Comment by blitzmann** [comment]
Can confirm. The projected remote capital boosters are not taking into consideration triage module bonus on projectees (it's projecting 300hp/s regardless, easily seen with eHP switched to raw). This seems like a minor oversight with how effects are ordered. I feel like we've had similar issues before, though I cannot remember off the top of my head exactly what was happening then. I don't have easy access to source code / dev environment, but hopefully this one's easy to fix

As for the negative sustained cap, Kadesh should look into that. I have no idea how sustained rates are calculated...But I can confirm that disabling triage module will bring the sustained rate to the correct value -- 0. Triage is definitely affecting it, not sure where. short fix might be to return 0 when value is negative.

**Comment by blitzmann** [comment]
I looked into this further. t indeed is a runtime issue. Setting the triage II effect to early runtime allows it to be processed before the shield transfers and result in proper stats when projected.

I want to test it a bit more tomorrow before committing.
