### ISSUE TITLE
importing wx fails in Debian 8

### ISSUE THREAD

**Issue by xalib** [DarkFenX/Pyfa#293]
On an uptodate debian 8 system the script fails at importing wx. 
wx is there and importable in python itself (>>>import wx runs, >>>help(wx) gives a return)
python pyfa.py 
wxPython 2.8 not found; attempting to use newer version, expect errors
Traceback (most recent call last):
  File "pyfa.py", line 82, in <module>
    import wx
ImportError: No module named wx

is it a wxPython2.8<=>wxPython3.0 error or is it a bug in pyfa?

**Comment by DarkFenX** [comment]
wx3 seems to be the only wx version available in debian 8. wx3 support is not merged into master yet - it's in wx3 branch.

Until it's merged into master, you can use wx3 branch (but it's quite buggy, see bugs with wx3 label), or make mixed system using apt-pin (there's 2.8 in debian unstable).

**Comment by blitzmann** [comment]
Gonna add a comment about this in README and close this.

fyi, easy apt-pining tutorial that I used to get both 2.8 and 3.0. If you want a stable program, continue with 2.8 for now.
http://jaqque.sbih.org/kplug/apt-pinning.html
