### ISSUE TITLE
microwarpdrive chanes carnyx stealth changes

### ISSUE THREAD

**Issue by Dunduro** [DarkFenX/Pyfa#296]
yo dude microwarp drives have had some stealth changes in carynx they are now 5MN 50MN 500MN to vaguely represent their speeds, this in it self isnt a major issue but the variable speed per MWD is no longer at a static 500%.

just wanted to give ya heads up.

Thanks for keeping your software up to date and running like a boss! use Pyfa on daily basis cheer!

**Comment by DarkFenX** [comment]
We have it covered :)
