### ISSUE TITLE
Double propulsion modules speed

### ISSUE THREAD

**Issue by unti1x** [DarkFenX/Pyfa#299]
1. Fit any propulsion module (see normal speed)
2. Fit another one. First module turns off, but speed being recalculated using old speed with first module on. E.g. basic speed - 383 m/s; with 5mn mwd II - 2826 m/s; fit second mwd - first module turned off, but speed recalculated to 16335 m/s. 

If import fitting with two propmods from clipboard, you'll have both of them turned on

**Comment by blitzmann** [comment]
Thanks. Helpful to note that you can toggle the MWDs again and it will correct itself. Seems to be an oversight of checking states as the module is being loaded or run through the calculations... not sure of the order here, but I'll check it out. =)

**Comment by blitzmann** [comment]
Fixed. What was happening was that when appending an item from the market, pyfa would turn the new module active and then recalculate the fit (which would recalculate with 2 active MWDs). It then goes through a process of checking all module states and deactivates any disallowed modules (like the other MWD). If any changes to states occur during this, that's a flag that the fit must be recalculated again. It's this second calculation that we are missing.
