### ISSUE TITLE
Tactical Destroyer Mode & Projection

### ISSUE THREAD

**Issue by Tynakuh** [DarkFenX/Pyfa#302]
Bonuses from modes when projecting a tactical destroy on another ship are applied. (If you project a svipul onto another ship, you will see the resistances on the ship rise if svipul is in defense mode)

**Comment by blitzmann** [comment]
Confirmed. Will look into it - thanks!

**Comment by blitzmann** [comment]
Seems to have been an oversight - the mode item was being included in projected fit effects. Should be fixed in next release. =)
