### ISSUE TITLE
OS X incorrect bitmap rendering

### ISSUE THREAD

**Issue by blitzmann** [DarkFenX/Pyfa#305]
Getting some black bitmaps on the wx3 branch on OS X, specifically the chrome tabs background (the tabs themselves are fine).

I may have botched the wx3 install on my OS X VM, which may be contributing to it, or may not. More testing needed preferably with someone that actually works with this OS.

**Comment by blitzmann** [comment]
This old commit that helped chrometabs rander properly may come in handy: 7db13bd3baf96b9e6b3d6ea825466b8a63714afa

**Comment by nizmogtr** [comment]
Can confirm tabs with black background still present...

**Comment by blitzmann** [comment]
Should be fixed with c2ca5dffe805b2cf1302378ddfe8e9fe05d50e80

Commit and issue say bitmap rendering, it's really a paining/brush issue. Whatev
