### ISSUE TITLE
Consider switching from .zip to .tar.X for linux releases

### ISSUE THREAD

**Issue by volftomas** [DarkFenX/Pyfa#310]
Hi,
first I want to say that I life Pyfa, it's awesome tool and very helpful. Only thing I would like you to consider is to switch linux releases to using compressed tarballs. They are much more common in linux world and it's little annoying to have to have zip installed just for pyfa. Something like bzip2 would work better.

Thanks for considering

**Comment by blitzmann** [comment]
We are going to be completely changing the way we package pyfa soon, so maybe this will be something to think about. @DarkFenX is heading up that department

**Comment by blitzmann** [comment]
Actually, gonna close this as github automatically supplies releases in `.tar.gz` format. Honestly, this is exactly the same as the `-linux` release, minus this file: https://github.com/DarkFenX/Pyfa-skel/blob/master/src/info.py (which doesn't really do anything to my knowledge)
