### ISSUE TITLE
Bastion module icon error

### ISSUE THREAD

**Issue by glguy** [DarkFenX/Pyfa#317]
When I open a fit using a "Bastion Module I" I get an error dialog "Couldn't add an image to the image list."

Version: 1.13.0
Operating System: Windows
Installer: EXE

**Comment by blitzmann** [comment]
Well that's weird. I've never seen it do that before. I don't even get any output to stdout/stderr.

**Comment by DarkFenX** [comment]
This happens because bastion image is 15x16 (which happens, in turn, because source image in CCP image export is 64x68). I will change icon update script to crop images to square before downscaling.

**Comment by blitzmann** [comment]
@Regner is this something that you can look into fixing at the source?

**Comment by Regner** [comment]
What the derp... will ask around but the art team is pretty busy so not sure if they will get around to it.
