### ISSUE TITLE
Missile Guidance Computers and Enhancers don't show

### ISSUE THREAD

**Issue by greftek** [DarkFenX/Pyfa#319]
After installing the Aegis update (1.13.0) I wanted to test the new modules but they do not show up or expand properly.
![screenshot 2015-07-08 13 04 26](https://cloud.githubusercontent.com/assets/7336387/8568860/1b046bf6-2572-11e5-92ee-ce27739b96d4.png)

**Comment by DarkFenX** [comment]
This is bug on CCP's side. They're (or at least, were on release) in tracking computers and tracking enhancers market groups. Search for 'guidance' to access them conveniently.
