### ISSUE TITLE
t3d fits are created w/o mode selector

### ISSUE THREAD

**Issue by DarkFenX** [DarkFenX/Pyfa#321]
It appears to happen until you open existing hecate fit with mode. After that, new fits are created with mode.

**Comment by DarkFenX** [comment]
Apparently it happens to all t3ds, not just hecate. I assume it might be connected with autocleanup we implemented before this release.

**Comment by DarkFenX** [comment]
Also there're tracebacks, but they look like consequence of this issue:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_core.py", line 14665, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/home/av/Workspace/eve/pyfa/gui/builtinViews/fittingView.py", line 494, in spawnMenu
    menu = ContextMenu.getMenu(selection, *contexts)
  File "/home/av/Workspace/eve/pyfa/gui/contextMenu.py", line 75, in getMenu
    sub = m.getSubMenu(srcContext, selection, rootMenu, it, rootItem)
  File "/home/av/Workspace/eve/pyfa/gui/builtinContextMenus/tacticalMode.py", line 45, in getSubMenu
    menuItem.Check(self.currMode.item == mode.item)
AttributeError: 'NoneType' object has no attribute 'item'
```
I have no specific scenario which leads to it.

**Comment by blitzmann** [comment]
IIRC, tactical destroyers were always "created" with a None mode in the database. Only when the user changes it is the database updated.

ninja edit: with your traceback, it seems mode isn't being set with initialization? I specifically tested for this. What does this break? Can you no longer load fits or set modes?

**Comment by DarkFenX** [comment]
You can load existing fits just fine. You can't create new ones with mode right after pyfa is launched. It gets fixed at some point, however i didnt trace exact conditions for that.

**Comment by DarkFenX** [comment]
And i just couldn't reproduce it with confessor... going to try to find another steps.

**Comment by DarkFenX** [comment]
Ok, it's random, with approximately 50/50 chances.

**Comment by blitzmann** [comment]
I was able to reproduce, but yeah it's tricky. I can reproduce with only one of my fits. I'll look into this further tonight.

**Comment by blitzmann** [comment]
Actually, seems to be pretty easy:

        if self.modeID and self.__ship:
            item = eos.db.getItem(self.modeID)
            # Don't need to verify if it's a proper item, as validateModeItem assures this
            self.__mode = self.ship.validateModeItem(item)

This fetches the item and validates it as a mode. If the item is not valid, a mode is forced. However, this isn't run if there is no mode set, and as previously stated the mode is only set if the user sets it. so new fits that are created and not set, then pyfa is restarted, and the fit is loaded, will bypass this altogether.

I'll get a fix pushed soon

I think this is serious enough to warrant another release. Ugh.
