### ISSUE TITLE
Same fleet booster will not immediately apply to ships projecting onto each other

### ISSUE THREAD

**Issue by Moatman** [DarkFenX/Pyfa#329]
If you set a fleet booster for two ships in the projection preview, and then project one onto the other (A and B, respectively), the boosts will not apply to ship B until it's no longer the focus of the window (e.g. switching tabs or opening another fit)
Fleet boosts still apply normally to A.
[Example](http://i.imgur.com/6Luo0ZF.gif)
Edit: Having a ship project onto itself doesn't cause the delay

**Comment by blitzmann** [comment]
Yeah, this is a bug that's been around for a while. I noticed it (or probably caused it) back when I did some fixes to projections last year. Look at #99. It was fairly minor, but I might take a look at it again since I'm poking around that part of the code again. We'll see.

**Comment by blitzmann** [comment]
was fixed with f591ecba103029fa3a9ca1b612caf427f5a3ad86
