### ISSUE TITLE
T3 Strategic Cruisers can't be fitted

### ISSUE THREAD

**Issue by Soolarize** [DarkFenX/Pyfa#341]
Hi guys, 

First of all thanks a lot for the hard work, us Mac users desperately needed a Mac-compatible fitting tool.

Now to my issue: how come I can't see the T3 strategic cruisers fittings at all? Have a look at my screenshot, impossible to create a proper fitting for any of them. 
![screen shot 2015-07-30 at 12 32 25](https://cloud.githubusercontent.com/assets/11295328/8982227/0ebfde42-36b7-11e5-89db-6b9306186dd2.png)

**Comment by narthollis** [comment]
Try adding some subsystems.

t3 cruisers don't have any module slots themselves, they are provided by
the subsystems.

**Comment by blitzmann** [comment]
What he said. you must install 5 subsystems in order to make a complete ship. Once you do this, should work like any other fitting.

Gonna close this issue. Feel free to continue to comment if you have any questions
