### ISSUE TITLE
Tactical Destroyers - Sharpshooter mode does not update range

### ISSUE THREAD

**Issue by Nahaz** [DarkFenX/Pyfa#344]
Compared to EFT and tried back and forth in pyfa on Hecate with 150mm rails. Optimal does not change when setting to sharpshooter mode.

Example with Caldari Navy AM S - Should be 15 (150mm Prototype or T2) but it shows 10.3

**Comment by blitzmann** [comment]
You forgot to mention which version you are using, but that's okay as I know you're using the test release. It was an oversight related to recent work on projections (the focus of the two test releases), and has already been fixed: 17733d5951c95e39a995e

This has been mentioned on the EVE Online forums as well. Unfortunately my account has lapsed, and so I cannot tell people they are using an unstable build. I will leave this open until the next release as there may be others that are curious.

btw, latest stable release is v1.13.2: https://github.com/DarkFenX/Pyfa/releases/tag/v1.13.2 =)

**Comment by Nahaz** [comment]
Oh I didn't know that I had unstable, I just downloaded the latest that the DL link sent me to :)
