### ISSUE TITLE
fitting a web improves dps in graph view

### ISSUE THREAD

**Issue by jordillo** [DarkFenX/Pyfa#347]
don't have time to fully figure this out right now, so i'l keep it short.

i was fitting a scythe fleet issue with RLM. when i added a web the dps in the graph went up. not just in the 10km range of the web but across the entire missile range. that seems wrong.  :-)

kind regards!

**Comment by blitzmann** [comment]
Seems we don't take the web range into account within the graph. Nice find. I will look into it, but can't promise it'll be fixed. Graphing support as it is now is very bare-bones and hacked together, so it may not be an easy fix.

**Comment by blitzmann** [comment]
Fixed with #381

**Comment by jordillo** [comment]
noice!

2015-10-27 0:32 GMT+01:00 blitzmann <notifications@github.com>:
