### ISSUE TITLE
Provide pyfa-1.14.0-galatea-1.2-win_wx3.exe

### ISSUE THREAD

**Issue by volftomas** [DarkFenX/Pyfa#348]
Hey,
how much work it would be to provide pyfa-1.14.0-galatea-1.2-win_wx3.exe ? Would like to test it out but I'm spoiled by easy installation with exe file :D

**Comment by blitzmann** [comment]
We aren't going to provide an installer version until we completely make the switch to wx3. We don't want people installing it over their current installation (as it's still in testing and we still need to tweak some stuff).

It's pretty easy to simply extract the wx3 version and run it as a standalone. The installer will come in due time. =)
