### ISSUE TITLE
No Battlecruiser Entry?

### ISSUE THREAD

**Issue by droppedoncaprica** [DarkFenX/Pyfa#349]
On Windows 10 at the latest non-w3 release, I noticed that normal Battlecruisers don't appear on the list of ships.  You can search "Hurricane" and find them, however all I can find are the Attack Battlecruisers on the list.

![capture](https://cloud.githubusercontent.com/assets/1487206/9569775/8de0af3a-4f3a-11e5-86c2-04257c6fbc14.PNG)

**Comment by Ereshgikal** [comment]
The Cane and the other regular BCs are found under "Combat Battlecruisers".

/Z

**Comment by droppedoncaprica** [comment]
Well I'm dumb, didn't notice that entry after combing through it a few times.  Nevermind!
