### ISSUE TITLE
Error in Windwos

### ISSUE THREAD

**Issue by neosilver-gk** [DarkFenX/Pyfa#352]
Here are the Problemdetails from Windows:

Problemsignatur:
  Problemereignisname:	APPCRASH
  Anwendungsname:	pyfa.exe
  Anwendungsversion:	1.13.3.0
  Anwendungszeitstempel:	549debdc
  Fehlermodulname:	ntdll.dll
  Fehlermodulversion:	6.1.7601.18939
  Fehlermodulzeitstempel:	55afd843
  Ausnahmecode:	c0000005
  Ausnahmeoffset:	0003d968
  Betriebsystemversion:	6.1.7601.2.1.0.256.1
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789

Hope I'm it's ok to post Errors here.

Edit: I have the pyfa-1.14.0-galatea-1.2-win-wx3 Version.

**Comment by droppedoncaprica** [comment]
```
Problem signature: 
Problem Event Name: APPCRASH 
Application Name: pyfa.exe 
Application Version: 1.13.3.0 
Application Timestamp: 549debdc 
Fault Module Name: ntdll.dll 
Fault Module Version: 6.1.7601.18939 
Fault Module Timestamp: 55afd843 
Exception code: c0000005 
Exception Offset: 0003d968 
OS Version: 6.1.7601.2.1.0.256.1 
locale ID: 1031 
Additional Information 1: 0a9e 
Additional Information 2: 0a9e372d3b4ad19135b953a78882e789 
Additional Information 3: 0a9e 
Additional Information 4: 0a9e372d3b4ad19135b953a78882e789
```

Translated the error message from German.  (Thanks Google Chrome!)

**Comment by blitzmann** [comment]
I don't think this is a pyfa-specific problem. We don't ship with an `ntdll.dll` file AFAIK. This could be a problem with your computer that only manifests when pyfa is run for whatever reason.  Google search `ntdll.dll crash` and try some of the solutions presented.

Does it happen when you do a specific sequence of stes, or just when pyfa starts? Does it happen with the non-wx3 version?

**Comment by blitzmann** [comment]
Gonna close this for lack of updates. Feel free to respond if needed =)
