### ISSUE TITLE
Cerberus statistics incorrect

### ISSUE THREAD

**Issue by mux** [DarkFenX/Pyfa#357]
Somehow Pyfa lets me fit 5 light drones on the Cerberus, even though it only has the drone bay capacity and the bandwidth for 3.

**Comment by droppedoncaprica** [comment]
You can put in too many drones in the drone bay / activate more than the ship has bandwidth.  Check the meters on the upper right and you should notice the drone meters will be over 100% capacity.

**Comment by blitzmann** [comment]
@droppedoncaprica is correct. Pyfa does not restrict the drone bay to only the ones that can fit.
