### ISSUE TITLE
Allow Resizable Additions Pane

### ISSUE THREAD

**Issue by Riifta** [DarkFenX/Pyfa#358]
Allow the below area to be resized by the user. This lets the user see more then the small amount of room allows at the bottom of the window in their cargo/drones etc areas without scrolling. Most of the time especially when full screened the ship fittings don't take up the entire space and a lot of whitespace is wasted that could be used for a larger additions pane.

![additons](https://cloud.githubusercontent.com/assets/9170186/10065554/306111b6-62cb-11e5-8419-4a32463958d5.png)

**Comment by blitzmann** [comment]
I am not opposed to this, but IIRC it is not an easy task. No promises =)

**Comment by blitzmann** [comment]
Done with 9465aceddbcf2870eacbf33e77597d21cae6c5c6

It wasn't as hard as I thought it would be. Had a bit of a hiccup on how to handle the toggle panel, but I got it working.

There is a minimum size of 200 for each the additions panel and the fitting panel. You can still toggle the additions panel to utilize the fitting panel at full size.

**Comment by Riifta** [comment]
I just want to say I love you.

**Comment by blitzmann** [comment]
<3
