### ISSUE TITLE
ImportError: No module named dateutil.parser

### ISSUE THREAD

**Issue by sdack** [DarkFenX/Pyfa#362]
This happened with the current wx3-release after installing it under Linux. It is only a missing package under Debian (Testing) and after installing the missing package (python-dateutil 2.2) does Pyfa start as expected. A pretty, little message instead of an error message may be preferred.

$ ./pyfa.py 
Traceback (most recent call last):
  File "./pyfa.py", line 97, in <module>
    import service.prefetch
  File "/home/sven/Downloads/Pyfa-wx3/service/__init__.py", line 9, in <module>
    from service.update import Update
  File "/home/sven/Downloads/Pyfa-wx3/service/update.py", line 26, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser

**Comment by blitzmann** [comment]
So, you were simply missing the `dateutil` package? It is listed as a requirement in the FAQ (granted, this should be in the README, I am not sure why I ever moved it).

I'll look to see what I can do about having this crash, as this is something that pops up now and then. I think we only use dateutil for one specific purpose that is essentially non-essential, so we might be able to ignore it.

**Comment by sdack** [comment]
On 27/09/15 14:28, blitzmann wrote:
>
> So, you were simply missing the |dateutil| package? It is listed as a 
> requirement in the FAQ (granted, this should be in the README, I am not sure 
> why I ever moved it).
>
> I'll look to see what I can do about having this crash, as this is something 
> that pops up now and then. I think we only use dateutil for one specific 
> purpose that is essentially non-essential, so we might be able to ignore it.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DarkFenX/Pyfa/issues/362#issuecomment-143550812>.
>
Yep, that was all. I don't think I ever needed the package before, so it stuck 
out and because the wx3 stuff is still work-in-progress from what I understand 
did I make a note. Just thought I would let you know. Other stuff was missing, 
too, but those have a nice message to them that says you need wxpython and 
sqlalchemy. May be nice if dateutil gets the same nice treatment, but that is up 
to you of course.

Anyhow, thanks for Pyfa! Been using it for a long time now and it has always 
been the best EVE tool for me. I like it even better than EFT. Cannot even say 
when I used EFT at last. It is years...

**Comment by minlexx** [comment]
At startup, pyfa checks for installed wxPython and sqlalchemy, but does not check for dateutil.
Maybe, it also should check that dateutil is installed, in the same way as for wxPython / sqlalchemy?

**Comment by blitzmann** [comment]
fixed  6ed81e9baeb90aa8598b010cb8bc4570a4e2
