### ISSUE TITLE
Suggestion: Confirm when deleting a fit

### ISSUE THREAD

**Issue by resinneublem** [DarkFenX/Pyfa#363]
_Sorry for the spam, I'm just going to spin up a few threads as suggestions from using pyfa a lot_

If you accidentally click "delete" on a fit, poof it's gone immediately. That makes renaming fits a little scary since the buttons are so close.

**Comment by blitzmann** [comment]
I mean, I love it when I get GitHub notifications. =)

This has been something I've wanted to do for a while (see #129), but just haven't got around to doing. This can either be really easy with a simple dialog confirmation, or a little more difficult but nice looking with replacing the buttons themselves with the confirmation message.

**Comment by resinneublem** [comment]
Yeah. Undo would be great, but I do disagree with @DarkFenX on deleting a ship fit:

> I hate modal window approach. Any good UI should let do something unconditionally and provide some way to undo it.

At the very least, offering the modal as a preference in the settings area could allow people to choose what they prefer.

**Comment by blitzmann** [comment]
I think he was talking about in general (and may have also been a misunderstanding with what I was talking about in OP, as I didn't mention undo/redo functionality >_>). For something like deleting a fit, I think a dialog is appropriate. Maybe add a modifier (Lick shift+click) to bypass dialog confirmation for those that want to quickly delete their 50 rifter fits

**Comment by resinneublem** [comment]
> Maybe add a modifier (Lick shift+click) to bypass dialog confirmation for those that want to quickly delete their 50 rifter fits

Oh yeah, that's clever!

**Comment by blitzmann** [comment]
I went ahead and just did this with a confirmation dialog. I kept waiting to do this because I wanted to blend it in better with the UI, but fuck it, I've deleted fits by accident too and this is just too easy not to implement. =)

**Comment by resinneublem** [comment]
![](http://38.media.tumblr.com/60e8be5d65f13d1556f8eecdd9b55dd9/tumblr_mmjorvGXnJ1rm7gdlo1_400.gif)

Thanks man.
