### ISSUE TITLE
Suggestion: Setting to allow changing fit tabs with Ctrl-123 or Command-123 instead of Additions

### ISSUE THREAD

**Issue by resinneublem** [DarkFenX/Pyfa#365]
Asking for behavior like Chrome tabs, where you can quickly switch between fitting tabs (at the top) with either Ctrl-1, Ctrl-2, etc (or Command-1, Command-2 on the mac) instead of changing the Additions tabs.

**Comment by blitzmann** [comment]
Ctrl/Cmd+Pageup/Down should do it already. This doesn't give you the option of specifically saying "I want the fourth tab", but it should suffice.

**Comment by blitzmann** [comment]
Gonna close this as functionality is (mostly) there already.
