### ISSUE TITLE
Reproduceable crash on deleting fitting.

### ISSUE THREAD

**Issue by the-squid** [DarkFenX/Pyfa#371]
On 1.15.0 - with wx3 - pyfa stops responding any time I delete a fitting. Windows brings up the stopped responding dialog and has to force close pyfa.  The delete is successful on reload.

On windows 10 64 bit.  Installed with installer, which automatically removed the old installation.

**Comment by blitzmann** [comment]
Is there anything in the log file in the `.pyfa` directory?

**Comment by the-squid** [comment]
Log files are all empty :(

Yes, used wx3 installer.

Shift-click seems to cause the fit to delete without crashing.

**Comment by blitzmann** [comment]
I'm having a hard time testing this. It seems that every OS has it's own way of handing how to destroy a dialog, and these ways change from wx2.8 to 3.0. To make matters worse, I'm having a hard time (in linux anyway) differentiating this crash from #164. We'll see

**Comment by blitzmann** [comment]
Pretty sure that fixes it for all platforms.

**Comment by the-squid** [comment]
This started being less reproduceable for me, will try to remember to report back once I've played with parallax release for a while.

Cheers.
