### ISSUE TITLE
unable to rename characters

### ISSUE THREAD

**Issue by Listatta** [DarkFenX/Pyfa#377]
seem to be having same issue as poster: #983 - 2015-10-05 02:13:59 UTC from the EvEonline Forum Thread.

No matter what I seems to do I can not get the rename function to work, so only get new character and new character copy. running windows 10 64 bit. Asked corp mate to double check and he is having same problem.

also when i went to delete ship fitting it crashed.

**Comment by blitzmann** [comment]
Both issues have been fixed, see #371 and #375.

For the character rename / new character, hit enter. That may work (haven't checked). For the fit deletion, shift+click to delete without the dialog. Both these will be fixed with next release. =)
