### ISSUE TITLE
Unusable GUI in right-to-left environment

### ISSUE THREAD

**Issue by WiseFerret** [DarkFenX/Pyfa#378]
When starting pyfa on my system (ubuntu 15.10, Cinnamon DE, Hebrew interface) many columns and buttons are hidden, and the ships section is completely blank and cannot be interacted with (see screen shot).
![2015-10-10 23-06-04](https://cloud.githubusercontent.com/assets/1122205/10413019/9615fd02-6fa3-11e5-86e8-705893f1fff0.png)

**Comment by blitzmann** [comment]
Well that's interesting, and something I have no idea how to fix. I'll be honest, pyfa doesn't have great support for other locales, hence why everything is in english. I had no idea it would even render this way in such configuration - I figured an application would have to explicitly support it, but I guess the OS simply reverses the widgets?

Sorry, I don't really know where to even start to address this. Is there a way to launch pyfa in left-to-right mode, or are you forced to use right-to-left in every application if that's how the system is configured?

**Comment by blitzmann** [comment]
Also, I assume you're running from the python interpreter. If not, try to install the python packages required and run via interpreter. Any output in the terminal? How about in `~/.pyfa/log.txt`?

**Comment by WiseFerret** [comment]
There was no input in the terminal when I ran pyfa using "python ./pyfa.py" (is this the way to run in interpreter?), and the log file is empty.

Programs can be forced to run in LTR mode with "LC_ALL=C ./pyfa.py", but when using this workaround, as reported in issue #379, pyfa must be installed in an ascii path in order to run :-)

**Comment by blitzmann** [comment]
Ah, I didn't catch that part in the other issue. The unicode path issue should be much easier to solve. The RTL issue would require a complete reworking of the gui and how the sizers are created from what I understand poking through Google - not something that's really feasible atm. I'm going to mark this as wontfix,b ut will add a comment to the FAQ about how to get it to work properly by using `LC_ALL=C`

**Comment by WiseFerret** [comment]
This issue was solved for me with pyfa-20170111-29d0f1-linux.zip, The program now starts with English, left-to-right interface and works proerly.
