### ISSUE TITLE
Active Triage not effecting EW capacitor usage

### ISSUE THREAD

**Issue by wranders** [DarkFenX/Pyfa#380]
When Triage is active, EW modules, such as warp disruptors and scramblers, aren't showing the capacitor need adjustment.

Ex. Repub Fleet Warp Disruptor shows -4.2GJ/s with Triage active, when it should be reading -420,000GJ/s

**Comment by blitzmann** [comment]
Interesting... did the triage module always do this, or was it a balance change CCP did recently?

**Comment by wranders** [comment]
I've only recently got into carrier fitting, so I haven't noticed it before.
Doing research on it, there's mention of this change back on 2007, so it's pretty old.
Here's an old-forum post from CCP Fendahl regarding this:
http://eve-search.com/thread/524936-0/page/1#6

**Comment by blitzmann** [comment]
Fixed with 52464324205f34dd57e254f35e6c03d22739cf98

I also noticed that from EOS that some modifiers should be penalized and were not, so I fixed those as well. Hopefully they are correct. =)
