### ISSUE TITLE
Can pyfa 3x coexist with python 2.7 installed on system?

### ISSUE THREAD

**Issue by darkgreen** [DarkFenX/Pyfa#384]
I just installed the update (pyfa-1.15.0-vanguard-1.0-win-wx3.exe) and upon running it got an error out before any GUI:

    ---------------------------
    cx_Freeze: Python error in main script
    ---------------------------
    Traceback (most recent call last):
      File "C:\python-2.7.10\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
      File "E:\Coding\Python\Eve\Pyfa\library.zip\pyfa__main__.py", line 85, in <module>
      File "E:\Coding\Python\Eve\Pyfa\config.py", line 69, in defPaths
        sys.modules['__main__'].__file__))), sys.getfilesystemencoding())
    AttributeError: 'module' object has no attribute '__file__'
    ---------------------------

Now... looking at this I see that it references C:\python-2.7.10  which at first I thought was one of my own python 2.7 installs (of which I have multiple), but actually I don't even have that directory so I'm at a bit of a loss as to what's going on here. It looks like pyfa is looking for a module that isn't present? Perhaps someone familiar with the codebase can advise what is going on here? I do have multiple python 2.7 installs on the system, but the directory in that traceback is not one of them and does not exist. I know what freeze does but don't have cx_Freeze experience so I'm not sure if it's faking a directory or something.

edit by blitzmann - formatting

**Comment by narthollis** [comment]
(No idea what is causing this issue sorry, but thought I would clear up a couple of items for you)

CX_Freeze is the packaged used for bundling Pyfa into standalone executables. The likley reason you are seeing a reference to a CX_Freeze package in a python install you don't have is because this is the path on the system that version of Pyfa was packaged. 

Also, just a heads up - Github uses [Markdown](https://guides.github.com/features/mastering-markdown/) for its comment/message styling - so when you are posting a trace like that, it is best to have a blank line before and after, and wrap (place before and after) the trace in 3 back ticks (``` ` ```)

**Comment by blitzmann** [comment]
@narthollis is correct. `C:\python-2.7.10` is the path that I used to package the Windows build. I have no idea why cx_freeze keeps this path around, but it does display in it's errors.

As for your issue... we recently changed the packaging of pyfa, which is incompatible with the old structure. From the output that you gave, it shows that `pyfa.exe` is going to `library.zip` (which is part of the new packaging) to look for the main pyfa script, but then it goes to `config.py` which is in the root directory. `config.py` should be in `library.zip`.

It seems that you basically mixed the old structure with the new structure, which is confusing things. The new v1.15 installer tries to remove the previous installation, but if pyfa that wasn't technically installed at that location, it wouldn't remove the old files, and the new installer would simply overwrite the old stuff.

Anyway, to fix it, simply delete the directory (`E:\Coding\Python\Eve\Pyfa\`) and reinstall (if you save your user data in the root directory, make sure to save the `saveddata` directory before deleting the whole pyfa directory).

Let me know how it goes =)

**Comment by darkgreen** [comment]
Yup, manually clearing out the previous and running install again did the trick. To be honest I don't recall, I might have just cloned the previous install off github or something, I certainly spent some quality time reading your wxPython class structures :)

So I guess it went great =)

**Comment by blitzmann** [comment]
Yeah, if you want to run pyfa from it's source it best to keep that separate from the installed version, especially now that things are structured much differently. Glad you got it working =)
