### ISSUE TITLE
OS X shortcut for "Attribute Editor" conflicts with system "select all text"

### ISSUE THREAD

**Issue by pmcalpine** [DarkFenX/Pyfa#396]
Selecting all traffic in a text box should be able to be done by pressing cmd-A on OS X. Now it opens the "Attribute Editor" window. Could this hotkey please be change to something else so that we can select all entered text using the same shortcut used everywhere else on the platform?

**Comment by blitzmann** [comment]
Yes, didnt think of this. Im open to suggestions (maybe T)

**Comment by pmcalpine** [comment]
To me: cmd-T means "open tab". Given Pyfa has tabs this isn't my recommendation.

How about: cmd-B
I don't think that's anything.

**Comment by blitzmann** [comment]
Right, forgot about the tabs. B it is then!

**Comment by pmcalpine** [comment]
Thanks!
