### ISSUE TITLE
1.16.1 - issues with "reduction in cloaking devices cpu requirements"

### ISSUE THREAD

**Issue by msoltyspl** [DarkFenX/Pyfa#406]
Hopefully I didn't miss anything obvious this time. Since updating to 1.16.1 - "All V" character receives no bonus to cpu reduction for cloaks:

![pyfa-bug2a](https://cloud.githubusercontent.com/assets/3541095/10981402/eef9f5d6-8407-11e5-85c6-582046bf9761.png)

Note that my regular character with covops at IV receives proper 80% reduction though. When I force it to V, the same issue as with "All V" shows up.

Similarly - Astero ship with role bonus 100% reduction - shows no reduction at all (regardless of the character choice):

![pyfa-bug2b](https://cloud.githubusercontent.com/assets/3541095/10981518/7e3e3540-8408-11e5-9846-b67fc5b4fa1a.png)

**Comment by blitzmann** [comment]
That is very odd.

What other ship can give a module 100% reduction? I wonder if it's just bugging out due to logic of the percentage?

**Comment by blitzmann** [comment]
That was exactly it. Fixed in the repo =)

I'm hoping to fix a few other things, mostly linux-based bugs, and do another release in like a week or so.
