### ISSUE TITLE
Ubuntu 14.04 - git master - ImportError: cannot import name ssl_

### ISSUE THREAD

**Issue by bsmr** [DarkFenX/Pyfa#407]
My pyfa setup is based on a Ubuntu 14.04 system using the master branch. For python I only use the official Ubuntu repositories.

I can't really tell when it happened, but it was in the last few days, that pyfa did not start anymore. Instead I get the following error

```
shell$ ./pyfa.py 
Traceback (most recent call last):
  File "./pyfa.py", line 104, in <module>
    import service.prefetch
  File "/XXX/Pyfa/service/__init__.py", line 16, in <module>
    from service.pycrest import EVE
  File "/XXX/Pyfa/service/pycrest/__init__.py", line 13, in <module>
    from .eve import EVE
  File "/XXX/Pyfa/service/pycrest/eve.py", line 11, in <module>
    from weak_ciphers import WeakCiphersAdapter
  File "/XXX/Pyfa/service/pycrest/weak_ciphers.py", line 20, in <module>
    from urllib3.util import ssl_
ImportError: cannot import name ssl_
```

Could anyone help with this problem, please?!

**Comment by blitzmann** [comment]
Theres some others with the same problems. Do you have the requests and uckages python packages? This particular thing is actually from pycrest, the python Crest interface i use, so im not too familiar with it

**Comment by blitzmann** [comment]
I'm still not sure what the exact issue is here, but I did commit a fix to this. CREST apparently release with only weak cipher support, and so the file that is giving you trouble is one that implements weak ciphers. From what I've seen with my testing, CREST now accepts stronger ciphers and thus I can get rid of the problematic file. I still need to actually test on Linux and OS X, but I don't see why it wouldn't work. I'll make a new release soon with these changes.

**Comment by bsmr** [comment]
Sorry, I couldn't respond earlier.
I checkt for the packages:

```
$ dpkg --list 'python-*' | grep '^ii ' | grep requests
ii  python-requests                                             2.2.1-1ubuntu0.3                                    all          elegant and simple HTTP library for Python, built for human beings
ii  python-requests-whl                                         2.2.1-1ubuntu0.3                                    all          elegant and simple HTTP library for Python, built for human beings
bsmr@abyss:~
$ dpkg --list 'python-*' | grep '^ii ' | grep urllib
ii  python-urllib3                                              1.7.1-1ubuntu4                                      all          HTTP library with thread-safe connection pooling for Python
ii  python-urllib3-whl                                          1.7.1-1ubuntu4                                      all          HTTP library with thread-safe connection pooling
```

From a Google search I believe I found an information, that ```urllib3``` _may be too *old*_: [Stackoverflow: ImportError: cannot import name SSLError](http://stackoverflow.com/a/20927907).
Well I am no Python programmer, so I can't tell if that's the right _direction_, on the other hand, I don't want to manually install a newer version.

I will check Your commit in a few minutes...

**Comment by bsmr** [comment]
Just pulled latest ```master```... it starts up again.

Thank You very much for Your quick help!

**Comment by blitzmann** [comment]
Yeah, my `urllib3` is 1.12, so that may be it. It shouldn't matter now as long as the CREST connections work without the weak ciphers. =)
