### ISSUE TITLE
Prices not loading in 1.16.1 -mac-wx3

### ISSUE THREAD

**Issue by thorr18** [DarkFenX/Pyfa#410]
Some module prices, such as for the Drone Link Augmentor II, are missing and instead showing: (!)
Others I have seen show a price followed by a (!), but the (!) goes away when I toggle to a different fit and back.  This does not correct the modules that are missing the price entirely, only the ones that show a price followed by the (!). 
I am seeing prices displayed for all modules in 1.15, but not in 1.16 .1  - Will attach image comparing. 
I have not seen any of the (!) marks on 1.15. 

<img width="930" alt="screen shot 2015-11-06 at 10 33 04 am" src="https://cloud.githubusercontent.com/assets/3753521/11006026/45e17c84-8476-11e5-8a06-97df4513d8ad.png">

**Comment by blitzmann** [comment]
Works fine for me on x1.16.1. The `(!)` means that the price update failed for some reason. This is most likely due to a network issue or something going on with EVE Central where we pull the prices from.

Try again later. Alternatively, right click the price pane (where it shows the total for ship and mods) and clear the cache to force a refresh. Let me know if the problem persists.

**Comment by blitzmann** [comment]
Also, keep in mind that failed price updates are subject to a (I think) 4 hour waiting period before they are requested again. But clearing the price cache will allow immediate re-request

**Comment by thorr18** [comment]
Here are the steps I'm doing now to duplicate: 
*Refresh the price cache on 1.16.1 which causes all the prices to go to (!). 
*Close it and open 1.15, which now displays the (!). 
*Refresh the cache from here corrects all the prices. 
*Close it and open 1.16.1, which now displays all the prices just loaded into the cache using 1.15
*Clear the cache to again display all (!). 
*Repeat ad infinitum. 
The problems I am having are on `-mac-wx3` 1.16.1

**Comment by thorr18** [comment]
I am getting all price fails when running PyFA from downloaded package, however I'm getting all price successes when running PyFA from source. 

I was able to run PyFA from PyCharm IDE and compare the 'about' window with my downloaded -mac-wx3 release. Everything shows the same, except I have a newer SQLalchemy on the one I'm running from source. 
<img width="1680" alt="screen shot 2015-11-10 at 12 45 36 am" src="https://cloud.githubusercontent.com/assets/3753521/11059288/a728eb06-874d-11e5-9878-58c8aec936a4.png">

**Comment by blitzmann** [comment]
Thanks for the additional info. So none of the prices are working for you in the packaged version? That's strange. Double check in the preferences that you have network access enabled for price fetching.

**Comment by thorr18** [comment]
They both load settings from the same place; if I change one, it gets reflected on the config for the other when I open it. The network setting that is working for one is not working for the other. 

I originally reported this issue as affecting only some modules because I didn't know about clearing the price cache; I didn't realize most prices were carrying over from previous versions cache. 
To be clear: no non-cached prices have ever loaded for me when using either 1.16.1 or 1.16.2 downloaded builds. 
I do always get successfull price-loads when running 1.15.x or when running newest source in the IDE, though I don't know if all my external libraries are exactly the same or what other differences might exist in those packages. 

<img width="473" alt="screen shot 2015-11-10 at 10 55 08 am" src="https://cloud.githubusercontent.com/assets/3753521/11072661/ab124a66-879b-11e5-93be-1ae2adfee257.png">

**Comment by blitzmann** [comment]
I just tested this tongiht with both the basic and `wx3` build of v1.16.2, and my prices download fine. For good measure, I deleted my user database (which contains the price cache) just to be on the safe side and loaded a recent Titan kill from zKill using modules I know I never use. Works fine.

If you know anyone else with a mac that can test it, please have the speak up in this thread to confirm

**Comment by thorr18** [comment]
I did not try deleting my user database, or any other steps to test the downloaded build in a more clean environment. Is there a directory of cached settings/data somewhere I should try renaming ?
My testing was on OSX 10.10 & 10.11

**Comment by thorr18** [comment]
I just tested with the non-wx3 version, and the price loading works fine. This is a wx3 issue only.

**Comment by thorr18** [comment]
Thanks, I confirmed the issue persists with a clean ~/.pyfa

**Comment by simonszu** [comment]
I tested it on my setup, on 10.10 with wx3, also with the modules shown in the screen shot in the first post. I noticed that price calculation takes a little more time than on non-wx3 (maybe half a second vs no time on non-wx3), but while pyfa does this, a little icon with two circular arroes is shown, so no big deal. 
But, yeah, all prices load correctly. No problem for me.

**Comment by thorr18** [comment]
This issue happens for me 16.1 & 16.2 mac wx3 builds. 
Right now, my testing is not having the problem at all on 16.3 or 17.x builds.
