### ISSUE TITLE
[OSX] Pyfa becomes unresponsive after adding an item to cargo hold and changing its quantity

### ISSUE THREAD

**Issue by noenedrops** [DarkFenX/Pyfa#413]
Steps to reproduce:
1. Search for an item in the sidebar
2. Drag-n-drop it to Cargo tab of your fit
3. Right-click > Change quantity > Set new quantity

The outcome:
- the app starts beeping with generic osx error sound (sorry, don't know how to describe it better) on any click in the app window
- all controls of the app become unresponsive
- hotkeys stop working, even system ones (like ⌘Q)

OSX version: 10.10.4
Pyfa version:  1.16.1 wx3

**Comment by blitzmann** [comment]
This is probably a dialog issue. See #306. I must have missed this one in particular. Will fix, test, and a new release should be out in a few days. =)

**Comment by blitzmann** [comment]
Should be fixed with latest master.
