### ISSUE TITLE
feature request: notes tab

### ISSUE THREAD

**Issue by sup3rb** [DarkFenX/Pyfa#420]
It would be very helpful to have a tab for plain text notes.  In the additions window would be a good place for it.

I have a wide range of fits and purposes stored, and sometimes I go quite a while before returning to a fit.  It would be great to have some notes stored.  I could have thoughts recorded on how I thought the fit performed, what matchups I'm looking to fight or avoid, what areas I was working on improving, etc.  Or when I want to change that fit slightly for specific circumstances or lower-skill corpmates.  Etc. etc. etc.

BTW, thanks for this tool.  It is extraordinarily useful and I'm very thankful for it.

**Comment by blitzmann** [comment]
Duplicate #364. I think it would be a good idea, just need to get around to it.
