### ISSUE TITLE
Ship stats window does not appear, 1.16.2, not -wx, OSX 10.7.5

### ISSUE THREAD

**Issue by SuperiorMonkey** [DarkFenX/Pyfa#427]
Right-clicking in the ship fitting window and selecting Ship Stats does not always result in a pop-up with the ship info. After repeatedly going in and out of a fit, now it works. however on first loading it did not.

**Comment by blitzmann** [comment]
I cannot reproduce on 10.10.5. both basic and `wx3` versions work fine for me. I do not have a previous version of OS X to test with. If you can consistently reproduce this, please run the pyfa executable directly from from the terminal at `pyfa.app/Contents/MacOS/pyfa` with the `-d` flag; hopefully you can get some more info on why it might not be working.

**Comment by SuperiorMonkey** [comment]
The problem seems to have disappeared on its own, not sure what the issue was. If it shows up again I will report back here.
