### ISSUE TITLE
Right-clicking sometimes refuses to work

### ISSUE THREAD

**Issue by Zumochi** [DarkFenX/Pyfa#428]
Since the move to wxPython I sometimes can't right click anymore in Pyfa. This usually comes with another problem: the inability to move modules from one slot to another.

Closing and re-opening Pyfa fixes the issue.

Tested on both Windows 7 and Windows 10 (completely different computers).

Let me know if you want more details.

**Comment by blitzmann** [comment]
Do you have more descriptions of symptoms? What exactly are you trying to right click when these problems happen? Is it reproducable? Can you check the log file in the .pyfa directory in you user directory?

**Comment by Zumochi** [comment]
I'll try to write them down immediately when they happen next time.

It's basically with right-clicking all the essentials: ships, market items, modules in a fitting, the fitting window itself, possibly also the stat/attribute panel but I can't say entirely sure.

**Comment by sup3rb** [comment]
I have also seen this issue, cannot reliably reproduce yet.

**Comment by blitzmann** [comment]
Any progress with this?

**Comment by Zumochi** [comment]
I haven't had the time nor need to theorycraft a lot last week. I'll mess around a bit now.

**Comment by Zumochi** [comment]
I'll close the issue until I or someone else has found a way to replicate it.
