### ISSUE TITLE
Scripted Tracking Computers do not remove the unscripted bonus

### ISSUE THREAD

**Issue by paxswill** [DarkFenX/Pyfa#430]
The info for the Optimal Range script has a -100% bonus to the tracking speed bonus of the module it's loaded into, but that doesn't seem to be applied. This might be related to the bug in #406, and might have a similar fix, but I'm not really familiar with this codebase.
![screenshot 2015-11-13 19 35 19](https://cloud.githubusercontent.com/assets/178273/11160829/c3b51112-8a3d-11e5-9a2f-a8006a8e14df.png)
![screenshot 2015-11-13 19 35 22](https://cloud.githubusercontent.com/assets/178273/11160830/c3b7af9e-8a3d-11e5-98b3-355f83277264.png)
![screenshot 2015-11-13 19 35 41](https://cloud.githubusercontent.com/assets/178273/11160831/c3b88932-8a3d-11e5-83e2-7ee78517d1c9.png)

**Comment by thorr18** [comment]
Looks like dupe for #409

**Comment by blitzmann** [comment]
Make sure you are using v1.16.2 as this bug was fixed. If you are still experiencing the bug, please reopen and post exact fit, but as of right now I cannot reproduce
