### ISSUE TITLE
Incorrect CovOps Cloaking Device CPU requierement on the Astero

### ISSUE THREAD

**Issue by simonszu** [DarkFenX/Pyfa#431]
Hey,

i was searching for some Astero fittings on the web, and got a little confused, since every fitting was shown as "too much cpu" in Pyfa, even the fittings marked as "newbie" in the Uniwiki. So i did some research and found that one of the trait of the Astero is a 100% reducement in CovOps Cloaking Device CPU usage. When considering this, everything is okay and the CPU usage is under 100%. But this is incorrectly shown in Pyfa, so i am submitting this as a bug.

**Comment by blitzmann** [comment]
Make sure you are running the latest version: 1.16.2 - this was fixed in that version
