### ISSUE TITLE
Pyfa 1.16.2 wx3 OSX character editor API SSL issues

### ISSUE THREAD

**Issue by dangayle** [DarkFenX/Pyfa#432]
Trying to add a character using the API, but I keep getting the following errors:

![screen shot 2015-11-14 at 11 26 26 pm](https://cloud.githubusercontent.com/assets/129611/11167816/c2b5d554-8b27-11e5-99ba-275813d2f153.png)

![screen shot 2015-11-14 at 11 25 54 pm](https://cloud.githubusercontent.com/assets/129611/11167815/c2b5395a-8b27-11e5-94b7-9f8227a40b07.png)

Here's the about page:
![screen shot 2015-11-14 at 11 28 17 pm](https://cloud.githubusercontent.com/assets/129611/11167820/d08246c2-8b27-11e5-9fc5-dab68e5ec0f7.png)

Using the older Pyfa, I get no such errors :(

**Comment by simonszu** [comment]
Same here. The non-wx3-version for mac has no such errors.

**Comment by blitzmann** [comment]
Using the API or using CREST?

**Comment by simonszu** [comment]
CREST works without any problems, just for the records.

**Comment by dangayle** [comment]
CREST is fine, just the character editor, as far as I can tell.

**Comment by blitzmann** [comment]
OS X version guys?

**Comment by dangayle** [comment]
El Capitan latest

**Comment by simonszu** [comment]
Same here

**Comment by podwhitehawk** [comment]
OSX10.10.5 not working with same error
> SSL: CERTIFICATE_VERIFY_FAILED

**Comment by blitzmann** [comment]
I can't reproduce with 10.10.5 =(

**Comment by blitzmann** [comment]
We do ship with a new file: `pyfa.app/Contents/Resources/cacert.pem` which was needed for CREST things. What happens if you guys remove this file?

**Comment by blitzmann** [comment]
Do you guys get the same error with the non-wx3 build?

**Comment by blitzmann** [comment]
From what I can gather:

The old mac build was built with Python 2.7. The updated build is 2.7.10. Starting with 2.7.9, `urllib2` verifies the authenticity of the SSL certificate by default.

This might actually be a problem with the way py2app packaged the build. I inserted some command into `pyfa.py` and this is what printed out:

```
DefaultVerifyPaths(cafile='/opt/local/etc/openssl/cert.pem', capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/opt/local/etc/openssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/opt/local/etc/openssl/certs')
```

I am thinking that py2app bundled the binaries pointing to my development environment, which is why I can't reproduce (because I'm running the app on my dev environment). Obviously you guys don't have a dev environment set up, so I expect that these paths don't exist for you.

#### What I need you to do:
To verify my suspicions, please open `pyfa.app/Contents/Resources/pyfa.py` and at the top after `import config` add this:

```
import ssl
print ssl.get_default_verify_paths()
```

Then run pyfa with `path/to/pyfa.app/Contents/MacOS/pyfa -d`

It should print out a line with paths as it's first bit of info. Please post this, and then let me know if those paths even exist.

**Comment by blitzmann** [comment]
Also, I wonder if this is also the reason why so many OS X users are running old versions. When checking for new releases, we use a secure connection to the GitHub api, and it simply fails silently if there's an error.

Can you guys also download the 1.16.1-mac-wx3 release from here and tell me if you get a notification that v1.16.2 is available:
https://github.com/DarkFenX/Pyfa/releases/download/v1.16.1/pyfa-1.16.1-parallax-1.0-mac-wx3.zip

**Comment by blitzmann** [comment]
And honestly, there is a fix that will allow us to ignore the validity of the certificate. Since we're just dealing the the API, it's not imperative that we are absolutely 100% sure it's the eve server or not. This isn't a banking program ;)

**Comment by podwhitehawk** [comment]
@blitzmann 
tried download and run 1.16.1 wx3 and yes, there was no notification about available update

**Comment by dangayle** [comment]
This is on my work development machine, which has all the xcodes and brew installed.
```
$ pyfa.app/Contents/MacOS/pyfa -d
Nov 17 13:04:50  pyfa[15946] <Notice>: DefaultVerifyPaths(cafile=None, capath=None, openssl_cafile_env='SSL_CERT_FILE', openssl_cafile='/opt/local/etc/openssl/cert.pem', openssl_capath_env='SSL_CERT_DIR', openssl_capath='/opt/local/etc/openssl/certs')
Nov 17 13:04:50  pyfa[15946] <Notice>: 2015-11-17 13:04:50,807 root                     INFO     Starting pyfa
Nov 17 13:04:51  pyfa[15946] <Notice>: 2015-11-17 13:04:51,402 STDOUT                   INFO     applying update
Nov 17 13:04:51  pyfa[15946] <Notice>: 2015-11-17 13:04:51,402 STDOUT                   INFO     8
Nov 17 13:04:51  pyfa[15946] <Notice>: 2015-11-17 13:04:51,478 STDOUT                   INFO     applying update
Nov 17 13:04:51  pyfa[15946] <Notice>: 2015-11-17 13:04:51,478 STDOUT                   INFO     9
Nov 17 13:04:51  pyfa[15946] <Notice>: 2015-11-17 13:04:51,488 STDOUT                   INFO     applying update
Nov 17 13:04:51  pyfa[15946] <Notice>: 2015-11-17 13:04:51,489 STDOUT                   INFO     10
```
But here's the catch: It still doesn't work:
![](http://i.imgur.com/8RrzLNk.png)

**Comment by dangayle** [comment]
Whoops, accidentally closed it

**Comment by blitzmann** [comment]
@dangayle did you check if the directories actually exist?

It's also interesting to note that you guys have `cafile = None` whereas I have a value. I'm trying to set up a fresh 10.10 install so that I can actually reproduce, but I'm thinking that the easiest thing to do would be to just simply ignore certificate checking.

**Comment by simonszu** [comment]
I have also Homebrew and the current version of Xcode installed. The Path /opt/local doesn't even exist on my disk.  So i checked the default Homebrew root, and voila, i seem to have the requested files in /usr/local, which is the standard root of Homebrew. So maybe include a switch a la "If the cert files aren't found in /opt/local, search for them in /usr/local?" 
I don't know if this is builtin Python functionality or if you specify the paths explicit in Pyfa's code.

**Comment by dangayle** [comment]
They do not exist.

I'm not in favor of broken SSL things, it could come back to bite you in the future. It's certainly easier to bypass and you're right that it isn't a banking app, but think of the poor folks in Russia or China or wherever who might actually need the security.

Worst case scenario: Someone creates a man in the middle attack, spoofing the eve servers, which gives the attacker the keys. Jita burns.

Worst worst case scenario: Some kid in China is playing through a proxy, but something something something .... DEAD. lol.

**Comment by blitzmann** [comment]
@simonszu pyfa does not explicitly set these variables, and I'm not sure why our paths are different. Hopefully it's as easy as setting an environment variable like I had to do to get `requests` working right with SSL (https://github.com/DarkFenX/Pyfa/blob/master/config.py#L95), it's something I will look into. I wonder where the windows build is looking for these and why it hasn't had a problem...

@dangayle - we'll get this settled, for the children!

**Comment by blitzmann** [comment]
One more thing from you guys:

can you give me the output of `openssl version -d`

**Comment by dangayle** [comment]
$ openssl version -d    
    OPENSSLDIR: "/System/Library/OpenSSL"

**Comment by blitzmann** [comment]
Shot in the dark, can you try this and see if it works:

http://eve-files.com/dl/275906

**Comment by podwhitehawk** [comment]
@blitzmann 
>$ openssl version -d
>OPENSSLDIR: "/opt/chefdk/embedded/ssl"

**Comment by blitzmann** [comment]
@podwhitehawk let me know if that test build works for you =)

**Comment by simonszu** [comment]
$ openssl version -d
    OPENSSLDIR: "/System/Library/OpenSSL"

Testing build works for me. "Successfully fetched Ryne Ikkara's skills from the EVE API"

**Comment by noenedrops** [comment]
@blitzmann I've grabbed the last file; 10.10.4 here,
```
$ openssl version -d
OPENSSLDIR: "/System/Library/OpenSSL"
```

but for the key with access mask = 8, both for single character and whole account, I get the following:

![](http://i.imgur.com/oHge3tS.png)

**Comment by podwhitehawk** [comment]
@blitzmann 
testing build works for me without api ssl errors

**Comment by blitzmann** [comment]
Good to hear. One osx bug down, like 20 to go haha

@noenedrops please email me your api details. Check readme for my email. That sounds like an xml parsing issue, which is weird.
