### ISSUE TITLE
Rapier has only 1 turret slot.

### ISSUE THREAD

**Issue by oapneat** [DarkFenX/Pyfa#433]
First time doing this so hope I don't miss out too much.

As far as I can see it's a simple issue. The rapier has only one turret hardpoint rather than the three is actually has. 

Am using pyfa 1.16.2 on arch.

**Comment by blitzmann** [comment]
I believe you are mistaken. The rapier only has 1 turret slot. It also has 3 missile slots and 4 high slots overall. From the game:

![rapier](https://cloud.githubusercontent.com/assets/3904767/11171056/325c467c-8bb4-11e5-8fd8-d5b307acca49.PNG)

**Comment by oapneat** [comment]
Hey wow, you are correct. Sorry about that. That change totally passed me by!
