### ISSUE TITLE
No CREST settings with 1.16.2. for Mac

### ISSUE THREAD

**Issue by vesapalmu** [DarkFenX/Pyfa#436]
It seems 1.16.2 on OS X is missing the CREST settings. I was expecting to find them in settings based on the CCP Dev blog post: http://community.eveonline.com/news/dev-blogs/save-ship-fittings-to-eve-online-from-kill-boards-and-external-applications/

This is what I get in Pyfa on Mac:
<img width="472" alt="pyfa_-_preferences_and_pyfa_1_16_2_-_python_fitting_assistant" src="https://cloud.githubusercontent.com/assets/3542206/11209629/9a9d0996-8d22-11e5-86e8-0f0b6602b755.png">

**Comment by vesapalmu** [comment]
Oh, and Network is enabled, EVE servers are also enabled in the preferences.

**Comment by blitzmann** [comment]
You must have downloaded the `-mac` version, which uses old binaries (from like 2010). CREST and Attribute Editor support is explicitly disabled in this build. Instead, use the `-mac-wx3` version. This was addressed in the release notes for v1.16.2 =)

**Comment by vesapalmu** [comment]
That's correct. I'm using the default download for Mac. The problem was fixed by downloading the pyfa-1.16.2-parallax-1.1-mac-wx3.zip version.

**Comment by blitzmann** [comment]
BTW what OS X version are you running?

**Comment by vesapalmu** [comment]
For the benefit of anyone else googling the same problem:

Pyfa CREST menu hidden. Enabling CREST on Pyfa for Mac. Download a different version, see above.

I'm running OS X El Capitan, 10.11.1 and Pyfa 1.16.2.

**Comment by blitzmann** [comment]
Thanks, and I'm glad the wx3 versions works under 10.11 =)

**Comment by vesapalmu** [comment]
With a quick test, seems to work perfectly. Looks much better visually than the old version as well. Will submit tickets for any bugs I'll find.

Thanks for a great helper tool!

**Comment by blitzmann** [comment]
Yeah, the text rendering on Retina was improved with wxPython 3.0. The other text and icons that are blurry is still something that I need to address; subscribe to #398 for the latest on that problem

**Comment by vesapalmu** [comment]
The current version is a bit slow to render, but looks much better. An example how rendering an Atron looks like: https://gyazo.com/df8b6af9ad3e9fcc2ec78e654e8fe19d

**Comment by vesapalmu** [comment]
And this is on a very fast iMac with retina screen, i7 @ 4GHz, 16GB of memory, etc.

**Comment by vesapalmu** [comment]
The implicit mode for CREST works as expected. User-supplied details not so much. Will do some more work to figure out why it fails.

**Comment by blitzmann** [comment]
I've heard complaints about the speed of rendering, but I have not been able to reproduce on 10.10

Also, when changing modes, restart pyfa. Should work then - there's a few bugs with restarting the service after mode changes, but please let me know specifics if you can =)
