### ISSUE TITLE
CoreGraphics error prevents startup - OSX 10.7

### ISSUE THREAD

**Issue by SuperiorMonkey** [DarkFenX/Pyfa#437]
v1.16.2 / OSX 10.7.5

Same problem as seen on a previous Parallax version.
```
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]: Traceback (most recent call last):
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "/Applications/pyfa.app/Contents/Resources/__boot__.py", line 355, in <module>
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:     _run()
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "/Applications/pyfa.app/Contents/Resources/__boot__.py", line 336, in _run
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:     exec(compile(source, path, 'exec'), globals(), globals())
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "/Applications/pyfa.app/Contents/Resources/pyfa.py", line 99, in <module>
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:     import wx
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "wx/__init__.pyc", line 45, in <module>
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "wx/_core.pyc", line 4, in <module>
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "wx/_core_.pyc", line 14, in <module>
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   File "wx/_core_.pyc", line 10, in __load
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]: ImportError: dlopen(/Applications/pyfa.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so, 2): Library not loaded: /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   Referenced from: /Applications/pyfa.app/Contents/Resources/lib/python2.7/lib-dynload/wx/_core_.so
Nov 17 20:48:18 TheOctoBeast [0x0-0x2e82e8].org.evefit.pya[22432]:   Reason: image not found
Nov 17 20:48:18 TheOctoBeast pyfa[22432]: pyfa Error
Nov 17 20:48:20 TheOctoBeast com.apple.launchd.peruser.502[183] ([0x0-0x2e82e8].org.evefit.pya[22432]): Exited with code: 255
```
The problem here is fairly simple to figure out. /System/Library/Frameworks/CoreGraphics.framework does not exist in 10.7.5. Several things there as Core*, but no Graphics.

A quick googling explains the problem. In 10.7, CoreGraphics is inside the ApplicationSupport framework. Precise path is:
/System/Library/Frameworks/ApplicationServices.framework/Frameworks/CoreGraphics.framework/
I don't know how hard it is to get python to check that location if the standard one fails, but I can assure you that upgrading past 10.7.5 isn't an option for me. Incompatible BIOS, the only workaround I found involved hacking kernel files. :boom:

**Comment by blitzmann** [comment]
I was able to get 10.7.3 on a VM, and can definitely reproduce this problem. 

I am unfortunately not versed well enough with how mac works internally (such as their concept of Frameworks etc) or how these options differ from version to version to come to a good conclusion at the moment. Conversly, I'm also not well versed how libraries are linked when the binaries are built (and again, how these might differ between versions)

Please subscribe to #289 if you haven't already - I will be posting progress and calls for testing new mac builds on that issue.

**Comment by blitzmann** [comment]
Please check here and report back https://github.com/DarkFenX/Pyfa/issues/289#issuecomment-158735494

**Comment by SuperiorMonkey** [comment]
I was doing some research earlier, and it appears that the problem is with your compiler. To explain: Frameworks are just dynamic libraries with some nifty features added, like the ability to package header and nib files with the libraries, and the fact that multiple apps can use a single instance of the framework loaded into active memory.

Paths to frameworks are supposed to be done automatically by the compiler, *and* I found a reference that said that python is capable of using multiple framework locations for backwards compatibility. However, as the Apple dev docs state, "When you build an application or other executable, the compiler looks for frameworks in/System/Library/Frameworks as well as any other location specified to the compiler." Which sounds like you should be able to make a 10.10 compile that's backwards compatible with 10.7 and its different location, but the compiler will need some manner of flag informing it to look in two places for CoreGraphics.

I will continue this in the 289 thread, as there appear to be people there who know rather more than I do about this. :)

**Comment by blitzmann** [comment]
I'm closing this issue as we now have mac binaries that seem to work well. If problem persists wi the next release, please reopen
