### ISSUE TITLE
Notify user when altering user database

### ISSUE THREAD

**Issue by thorr18** [DarkFenX/Pyfa#447]
When a module doesn't load for whatever reason, eg it no longer exists in Eve or because that fitting slot no longer exists for the chassis, could we get a message to see what we've lost from our user database? Maybe something in the notes tab and/or log and/or pop-up ?

**Comment by blitzmann** [comment]
The log should already print an error:
https://github.com/DarkFenX/Pyfa/blob/master/eos/saveddata/module.py#L85

Whether or not this works in packaged build I have no idea. I've had too many problems in the past with logging with the distributive to be confident in it.

**Comment by thorr18** [comment]
Thanks. Do you think this applies when no slot can be found for the module because CCP took away a hardpoint ?

**Comment by thorr18** [comment]
This should log?
https://github.com/DarkFenX/Pyfa/blob/master/eos/saveddata/module.py#L543

**Comment by blitzmann** [comment]
I dont think it applies to modules when a slot is removed via ccp. Instead i think what happens is like when you change subsystems to remove slots and modules are still present: the slot turns a bright red. Not sure what happens if a hardpoint is remove thou, dont think weve ever tested for that
