### ISSUE TITLE
Modulated Strip Miner II displays wrong yield

### ISSUE THREAD

**Issue by cite** [DarkFenX/Pyfa#454]
The below fit with all three Mining Laser Upgrade II online will display a yield of 17.4/s. When put all ming laser upgrades offline, the yield is still 17.4/s. However, the "Mining amount" (Right click on Modulated Strip Miner II -> "Module Stats" -> "Attributes") goes down when disabling Minung Laser Upgrades.

This seems to work with the Mining Laser II and the Strip Miner I.

[Skiff, NullSec Serp (max yield)]

Mining Laser Upgrade II
Mining Laser Upgrade II
Mining Laser Upgrade II

Adaptive Invulnerability Field II
Survey Scanner II
Medium Shield Extender II
Thermal Dissipation Field II
Kinetic Deflection Field II

Modulated Strip Miner II, Bistot Mining Crystal II

Medium Core Defense Field Extender I
Medium Core Defense Field Extender I

Hornet EC-300 x5
Vespa II x5
Hornet I x5

Inherent Implants 'Highwall' Mining MX-1003

Veldspar Mining Crystal I x1

**Comment by cite** [comment]
NVM. Deleting the fit and re-adding it fixed the problem.

**Comment by blitzmann** [comment]
For future reference, if you look at items stats -> affected by tab, you can see everything that is affecting the stats of that item. So if you are noticing weird results, check that first. =)
