### ISSUE TITLE
Questions regarding multiple Pyfa installations

### ISSUE THREAD

**Issue by Zumochi** [DarkFenX/Pyfa#455]
1. I have two separate Windows installations on my computer I frequently use. As such it's annoying to export/import every time I swap and want to make use of Pyfa. Is it possible for Pyfa to make use of a database file from the other installation? Or should I copy over the db file?
2. Right now I have two separate db files with different fits, is it possible to somehow merge them or should I export from one and import to another?

**Comment by blitzmann** [comment]
1) a. It's very possible with the help of cloud storage (such as Dropbox or Copy). If you only use Windows, you can simply install pyfa to a sync'd directory, and then run pyfa with `-r` which will save the user database in the installation directory under `saveddata/`. Do be mindful, though, if you run with this configuration, that you must be careful not to delete the pyfa directory outright. In normal situations you can do this, but in this situation you will also delete your user data.

b. I personally like to use symlinks to avoid the above issue. An explanation can be found here:https://github.com/DarkFenX/Pyfa/wiki/Cross-Platform-Data-Sharing

2) It's not possible to merge the two databases together unfortunately. You will have to export from one and import from another (or you can File > Backup all fits from one and then import them to the other, but this will not check for duplicates in the receiving database).

Closing this as it's not an issue, but please feel free to continue the discussion if you have any questions =)

**Comment by Zumochi** [comment]
Thanks for the thorough explanation, it seems I need to do 2) and then 1) b. :)
