### ISSUE TITLE
Maelstorm: ancillary shield boosters (all sizes) ignore ship's boost bonus per level

### ISSUE THREAD

**Issue by msoltyspl** [DarkFenX/Pyfa#461]
Fit any ancillary shield booster (charged or not) and Pyfa will show the same boost amount for all-5 and all-0 characters (as well as any other regular character).

Cyclone (minmatar CBC) with the same bonus behaves properly, so it's prooly that ship-only issue.

**Comment by blitzmann** [comment]
Fixed, thanks!
