### ISSUE TITLE
Nestor falloff bonus does not get applied

### ISSUE THREAD

**Issue by sdack** [DarkFenX/Pyfa#464]
Hello,

I have had a look at the new remote armor repair changes and I have noticed that in the Singularity build of PYFA it did not apply the falloff bonus to the remote reppers.

On SISI can one see that the Nestor with large T2 remote reppers now has got a range of 28.8km, which is also shown by PYFA. The Nestor also gets a bonus to the falloff making it 8400m, where as PYFA only shows the unbonused value of 4200m.

Could you please look into this?

**Comment by blitzmann** [comment]
Thanks, you reported this just in time for me to fix it and make new builds before releasing. =D

**Comment by sdack** [comment]
On 08/12/15 17:39, blitzmann wrote:
>
> Thanks, you reported this just in time for me to fix it and make new builds 
> before releasing. =D
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/DarkFenX/Pyfa/issues/464#issuecomment-162956865>.
>
Well, I am glad that I did! *lol*
