### ISSUE TITLE
Browsing to new Command Destroyers or Logistics Frigates in Ship Browser causes unexpected error

### ISSUE THREAD

**Issue by Vatierville** [DarkFenX/Pyfa#467]
Evemon updated
create new plan, or open existing plan and select ship via Ship Browser
click on ship e.g. Deacon
encounted error
have cleared out data directory including settings.xml

EVEMon Version: 2.2.1.4022
.NET Runtime Version: 4.0.30319.42000
Operating System: Microsoft Windows NT 6.2.9200.0
Executable Path: "C:\Program Files (x86)\EVEMon\EVEMon.exe" 

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at EVEMon.SkillPlanner.EveObjectSelectControl.PlanToMasteryLevel(TreeNode node) in EVEMon\SkillPlanner\EveObjectSelectControl.cs:line 509
   at EVEMon.SkillPlanner.EveObjectSelectControl.UpdateContextMenu() in EVEMon\SkillPlanner\EveObjectSelectControl.cs:line 456
   at EVEMon.SkillPlanner.EveObjectSelectControl.SetSelectedObjects(IEnumerable`1 items) in EVEMon\SkillPlanner\EveObjectSelectControl.cs:line 353
   at EVEMon.Common.Controls.TreeView.OnSelectionsChanged() in EVEMon.Common\Controls\TreeView.cs:line 161
   at EVEMon.Common.Controls.TreeView.OnMouseDown(MouseEventArgs e) in EVEMon.Common\Controls\TreeView.cs:line 1004
   at System.Windows.Forms.TreeView.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.TreeView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Datafile report:
  eve-blueprints-en-US.xml.gzip (176KiB - 6de28a6ec8dc4fbfe35ca1f53436f11d)
  eve-certificates-en-US.xml.gzip (43KiB - 262b680086b94410fc9a21f8c852b369)
  eve-geography-en-US.xml.gzip (531KiB - c60dd6b987340ff7d848f7eedc5a39c4)
  eve-items-en-US.xml.gzip (1677KiB - fcdb5af1a3d05f1f7dfefd06a439ec83)
  eve-masteries-en-US.xml.gzip (19KiB - 520eb03a3117186ad27ea252f4110554)
  eve-properties-en-US.xml.gzip (47KiB - 516a2cba339f40a5fbb70e4000a23a33)
  eve-reprocessing-en-US.xml.gzip (87KiB - 2ed449a5edee013317538788ea0e2263)
  eve-skills-en-US.xml.gzip (22KiB - d2aba9bade5c32055f2423c6d04118b2)

Diagnostic Log:
0d 0h 00m 00s > Starting up
0d 0h 00m 00s > EveMonClient.Initialize - begin
0d 0h 00m 00s > Load Datafiles - begin
0d 0h 00m 03s > Load Datafiles - done
0d 0h 00m 03s > EveMonClient.Initialize - done
0d 0h 00m 03s > Settings.TryDeserializeFromFile - begin
0d 0h 00m 04s > Settings.TryDeserializeFromFile - done
0d 0h 00m 04s > Settings.Import - begin
0d 0h 00m 04s > EveMonClient.OnSchedulerChanged
0d 0h 00m 04s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 04s > EveMonClient.OnSkillQueueUpdated - Alexei Kautsuo
0d 0h 00m 04s > NotificationRefTypes.Import - begin
0d 0h 00m 04s > NotificationRefTypes.Import - done
0d 0h 00m 04s > EveMonClient.OnCharacterUpdated - Alexei Kautsuo
0d 0h 00m 04s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 04s > EveMonClient.OnSkillQueueUpdated - Moor Deybe
0d 0h 00m 04s > EveMonClient.OnCharacterUpdated - Moor Deybe
0d 0h 00m 05s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 05s > EveMonClient.OnSkillQueueUpdated - Charni Deybe
0d 0h 00m 05s > EveMonClient.OnCharacterUpdated - Charni Deybe
0d 0h 00m 05s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 05s > EveMonClient.OnSkillQueueUpdated - Managerie
0d 0h 00m 05s > EveMonClient.OnCharacterUpdated - Managerie
0d 0h 00m 05s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 05s > EveMonClient.OnSkillQueueUpdated - Markov Gideon
0d 0h 00m 05s > EveMonClient.OnCharacterUpdated - Markov Gideon
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 06s > EveMonClient.OnSkillQueueUpdated - Maleko Volundr
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Maleko Volundr
0d 0h 00m 06s > EveMonClient.OnCharacterImplantSetCollectionChanged
0d 0h 00m 06s > EveMonClient.OnSkillQueueUpdated - Odona Gideon
0d 0h 00m 06s > EveMonClient.OnCharacterUpdated - Odona Gideon
0d 0h 00m 06s > EveMonClient.OnCharacterCollectionChanged
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Alexei Kautsuo
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Moor Deybe
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Charni Deybe
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Managerie
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Markov Gideon
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Maleko Volundr
0d 0h 00m 06s > EveMonClient.OnCharacterPlanCollectionChanged - Odona Gideon
0d 0h 00m 06s > EveMonClient.OnMonitoredCharactersChanged
0d 0h 00m 06s > EveMonClient.OnAPIKeyCollectionChanged
0d 0h 00m 06s > EveMonClient.OnSettingsChanged
0d 0h 00m 06s > Settings.Import - done
0d 0h 00m 06s > Main loop - start
0d 0h 00m 06s > EveMonClient.Run
0d 0h 00m 09s > MarketUnifiedUploader.Start()
0d 0h 00m 09s > UpdateManager.ScheduleCheck in 00:00:10
0d 0h 00m 09s > MarketUnifiedUploader.OnStatusChanged - Initializing
0d 0h 00m 09s > MarketUnifiedUploader.EndPointsUpdating()
0d 0h 00m 09s > EveMonClient.OnServerStatusUpdated
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Alexei Kautsuo
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Maleko Volundr
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 1923695 (Alexei Kautsuo, Maleko Volundr)
0d 0h 00m 10s > EveMonClient.OnAPIKeyInfoUpdated - 1923695 (Alexei Kautsuo, Maleko Volundr)
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Moor Deybe
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Charni Deybe
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 1917340 (Moor Deybe, Charni Deybe, Sally the Seal)
0d 0h 00m 10s > EveMonClient.OnAPIKeyInfoUpdated - 1917340 (Moor Deybe, Charni Deybe, Sally the Seal)
0d 0h 00m 10s > MarketUnifiedUploader.OnEndPointsUpdated - EVE Market Data Relay
0d 0h 00m 10s > MarketUnifiedUploader.OnStatusChanged - Idle
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Maleko Volundr
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 3436668 (Maleko Volundr)
0d 0h 00m 10s > EveMonClient.OnAPIKeyInfoUpdated - 3436668 (Maleko Volundr)
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Managerie
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 2897576 (Managerie)
0d 0h 00m 10s > EveMonClient.OnAPIKeyInfoUpdated - 2897576 (Managerie)
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Markov Gideon
0d 0h 00m 10s > EveMonClient.OnCharacterUpdated - Odona Gideon
0d 0h 00m 10s > EveMonClient.OnCharacterListUpdated - 3244471 (Markov Gideon, Odona Gideon)
0d 0h 00m 10s > EveMonClient.OnAPIKeyInfoUpdated - 3244471 (Markov Gideon, Odona Gideon)
0d 0h 00m 11s > EveMonClient.OnCharacterContactsUpdated - Alexei Kautsuo
0d 0h 00m 11s > EveMonClient.OnCharacterStandingsUpdated - Alexei Kautsuo
0d 0h 00m 11s > EveMonClient.OnCharacterMedalsUpdated - Alexei Kautsuo
0d 0h 00m 11s > EveMonClient.OnNotificationSent - An error occured while querying the personal kill log.
0d 0h 00m 11s > ConquerableStationList.Import - begin
0d 0h 00m 11s > ConquerableStationList.Import - done
0d 0h 00m 11s > EveMonClient.OnCharacterContractsUpdated - Alexei Kautsuo
0d 0h 00m 11s > EveMonClient.OnContractsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterAssetsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.CharacterWalletTransactionsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterWalletJournalUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterResearchPointsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterIndustryJobsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnIndustryJobsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveNotificationTextParser.GetExternalParser - begin
0d 0h 00m 15s > EveMonClient.OnCharacterEVENotificationsUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Alexei Kautsuo
0d 0h 00m 15s > EveMonClient.OnCharacterStandingsUpdated - Moor Deybe
0d 0h 00m 15s > EveMonClient.OnCharacterContactsUpdated - Moor Deybe
0d 0h 00m 16s > EveMonClient.OnCharacterMedalsUpdated - Moor Deybe
0d 0h 00m 16s > EveMonClient.OnNotificationSent - An error occured while querying the personal kill log.
0d 0h 00m 17s > EveMonClient.OnCharacterAssetsUpdated - Moor Deybe
0d 0h 00m 17s > EveMonClient.OnCharacterWalletJournalUpdated - Moor Deybe
0d 0h 00m 17s > EveMonClient.OnCharacterContractsUpdated - Moor Deybe
0d 0h 00m 17s > EveMonClient.OnContractsUpdated - Moor Deybe
0d 0h 00m 17s > EveMonClient.OnCharacterIndustryJobsUpdated - Moor Deybe
0d 0h 00m 17s > EveMonClient.OnIndustryJobsUpdated - Moor Deybe
0d 0h 00m 17s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Moor Deybe
0d 0h 00m 18s > EveMonClient.CharacterWalletTransactionsUpdated - Moor Deybe
0d 0h 00m 18s > EveMonClient.OnCharacterEVENotificationsUpdated - Moor Deybe
0d 0h 00m 18s > EveMonClient.OnCharacterResearchPointsUpdated - Moor Deybe
0d 0h 00m 18s > EveMonClient.OnCharacterStandingsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Moor Deybe
0d 0h 00m 18s > EveMonClient.OnCharacterContactsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnCharacterMedalsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnNotificationSent - An error occured while querying the personal kill log.
0d 0h 00m 18s > EveMonClient.OnCharacterAssetsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnCharacterWalletJournalUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnCharacterContractsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnContractsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnCharacterIndustryJobsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.OnIndustryJobsUpdated - Managerie
0d 0h 00m 18s > EveMonClient.CharacterWalletTransactionsUpdated - Managerie
0d 0h 00m 19s > EveMonClient.OnCharacterResearchPointsUpdated - Managerie
0d 0h 00m 19s > EveMonClient.OnCharacterEVEMailMessagesUpdated - Managerie
0d 0h 00m 19s > EveMonClient.OnCharacterEVENotificationsUpdated - Managerie
0d 0h 00m 19s > EveMonClient.OnCharacterPlanetaryColoniesUpdated - Managerie
0d 0h 00m 19s > The type or namespace name 'EveNotificationTextParser' could not be found (are you missing a using directive or an assembly reference?)
0d 0h 00m 19s > The type or namespace name 'EveNotification' could not be found (are you missing a using directive or an assembly reference?)
0d 0h 00m 19s > EveNotificationTextParser.GetExternalParser - done
0d 0h 00m 19s > EveMonClient.OnCharacterContractBidsUpdated - Alexei Kautsuo
0d 0h 00m 19s > EveMonClient.OnCharacterContractItemsDownloaded - Alexei Kautsuo
0d 0h 00m 19s > EveMonClient.OnRefTypesUpdated
0d 0h 00m 19s > EveMonClient.OnCharacterContractItemsDownloaded - Alexei Kautsuo
0d 0h 00m 19s > EveMonClient.OnCharacterContractBidsUpdated - Moor Deybe
0d 0h 00m 19s > UpdateManager.BeginCheck
0d 0h 00m 19s > EveMonClient.OnCharacterEVEMailingListsUpdated - Alexei Kautsuo
0d 0h 00m 20s > EveMonClient.OnCharacterEVEMailingListsUpdated - Moor Deybe
0d 0h 00m 20s > EveMonClient.OnCharacterContractItemsDownloaded - Moor Deybe
0d 0h 00m 20s > EveMonClient.OnAccountStatusUpdated - 1917340 (Moor Deybe, Charni Deybe, Sally the Seal)
0d 0h 00m 20s > UpdateManager.ScheduleCheck in 12:00:00
0d 0h 00m 20s > UpdateManager.OnCheckCompleted
0d 0h 00m 20s > EveMonClient.OnCharacterContractItemsDownloaded - Moor Deybe
0d 0h 00m 20s > EveMonClient.OnAccountStatusUpdated - 1923695 (Alexei Kautsuo, Maleko Volundr)
0d 0h 00m 20s > EveMonClient.OnCharacterContractBidsUpdated - Managerie
0d 0h 00m 20s > EveMonClient.OnAccountStatusUpdated - 3244471 (Markov Gideon, Odona Gideon)
0d 0h 00m 20s > EveMonClient.OnAccountStatusUpdated - 2897576 (Managerie)
0d 0h 00m 21s > EveMonClient.OnAccountStatusUpdated - 3436668 (Maleko Volundr)
0d 0h 00m 21s > EveMonClient.OnCharacterEVEMailingListsUpdated - Managerie
0d 0h 00m 27s > EveMonClient.OnCharacterPlanCollectionChanged - Moor Deybe

**Comment by blitzmann** [comment]
Wrong issue tracker! This is the pyfa issue tracker. =P

**Comment by Vatierville** [comment]
arrrrrghhh thanks.
PYFA is brilliant BTW :-)
