### ISSUE TITLE
Rapid Heavy Missile Launchers are missing their icons

### ISSUE THREAD

**Issue by Hiwashi** [DarkFenX/Pyfa#468]
RHML are missing their small icons. Very minor issue but a bit annoying.

**Comment by thorr18** [comment]
I thought this was fixed for issue #452

**Comment by thorr18** [comment]
109_64_1.png.png was for the RHML, and is missing. 

These are the icons that are missing from 1.17.0 
~~~
icons/27_05.png
icons/26_16.png
icons/26_15.png
icons/26_13.png
icons/26_12.png
icons/36_15.png
icons/res:/ui/texture/icons/109_64_1.png.png
icons/res:/ui/texture/icons/109_64_2.png.png
icons/MarketIcon_16px_Caldari.png
icons/MarketIcon_16px_Amarr.png
icons/MarketIcon_16px_Gallente.png
icons/MarketIcon_16px_Minmatar.png
~~~

For reference, these were the icons missing from 1.16.x
~~~
icons/res:/ui/texture/icons/109_64_2.png.png
icons/118_2.png
icons/36_15.png
icons/res:/ui/texture/icons/109_64_1.png.png
icons/.png
~~~

**Comment by blitzmann** [comment]
I am not sure what the problem was - seems to have corrected itself with the latest EVE data. That being said, I did improve on the icon scripts, so now we have icons for all those cargo containers. =)
