### ISSUE TITLE
Can't import fits in osx wx3 pyfa - from win pyfa export - hangs at 0%

### ISSUE THREAD

**Issue by unpoetical** [DarkFenX/Pyfa#481]
I exported all my fits from a windows machine and transferred via dropbox to osx.   I just installed pyfa on OSX it may be one minor release ahead of the windows version.   I don't have access to the win box for the next month.   I've tried to import the file a few times and it just hangs at 0% and the elapsed timer says 0:00:00.

The file is 250kb and 4600 lines.

[pyfa-fits-20151220_025630.xml.zip](https://github.com/DarkFenX/Pyfa/files/69117/pyfa-fits-20151220_025630.xml.zip)

It behaves the same if I edit the file down to just one fit.

[single fit pyfa-fits-20151220_025630.xml.zip](https://github.com/DarkFenX/Pyfa/files/69121/single.fit.pyfa-fits-20151220_025630.xml.zip)

pyfa-1.17.1-frostline-1.0-mac-wx3.zip (downloaded 12/21) on El Capitan 10.11.2.

**Comment by blitzmann** [comment]
Duplicate #456 

Also, if you're wanting to migrate your fitting database, it's better to move the `saveddata.db` file in `~/.pyfa` to the new platform, or even using symlinks with cloud storage as described here:

https://github.com/DarkFenX/Pyfa/wiki/Cross-Platform-Data-Sharing

These methods will preserve not only fits, but boosters, gang links, characters, implants, etc
