### ISSUE TITLE
Cannot view Missing Skills list: OSX 10.7.5

### ISSUE THREAD

**Issue by SuperiorMonkey** [DarkFenX/Pyfa#483]
The book icon in the upper right corner is changing colors to show when a selected character is missing skills. However there is no longer a popup window showing what skills are missing. The Export Missing Skills menu item is operating normally as well, appears to be a display problem with the icon.

**Comment by blitzmann** [comment]
Try to hover for about 2 seconds. There is a known issue that, for some reason, tooltip delay was increased and I haven't found a good way to fix this yet. Let me know

**Comment by SuperiorMonkey** [comment]
Oh, there it is. Yeah that's slow, and worse any mouse action resets the
popup timer. So really have to sit and stare at it.

**Comment by blitzmann** [comment]
Duplicate #405.
