### ISSUE TITLE
"From Clipboard" fails silently for fits with empty slots

### ISSUE THREAD

**Issue by xorxcel** [DarkFenX/Pyfa#494]
Pyfa always seems to fail to import an eft fitting which contains empty slots. Example:
_________________________________
[Obelisk, Test]

Inertial Stabilizers II
[Empty Low slot]
Inertial Stabilizers II
_________________________________
when trying to import this fitting via the clipboard, nothing happens, not even an error message is displayed.
Removing the "[Empty Low slot]" line (or filling this slot in the fit) fixes the problem.

pyfa version: 1.17.1 Stable, installed on Arch Linux via AUR

**Comment by blitzmann** [comment]
Known issue, already fixed. Will be available next release
