### ISSUE TITLE
Gang bonus calculation issues when projecting boosting ship onto fit

### ISSUE THREAD

**Issue by dachucky** [DarkFenX/Pyfa#75]
As per the subject, there seems to be something going wrong with the calculations when projecting <code>A -> B</code> when <code>B</code> is being boosted by <code>A</code>.

Examples:

Claymore with Shield Harmonizing Link projects onto unfit Retribution. Then set Claymore as Squad Booster. Notice that Retribution gets no bonuses.

Remove Claymore as booster and projected fit. Set Claymore as Squad Booster. Then project Claymore fit onto Retribution. Notice that Shield Harmonizing bonus is removed. Then remove Claymore from projected fits. Notice that all gang bonuses are removed, despite Claymore still being listed as Sqaud Booster.

**Comment by blitzmann** [comment]
This should be fixed with latest commit in master (e74e2615ad45f00a200477e880e61b67e6f153eb). If not, please reopen. =)
